/*
 * File: app/view/About.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DNB.view.About', {
    extend: 'Ext.Container',
    alias: 'widget.about',

    requires: [
        'Ext.Img',
        'Ext.Panel',
        'Ext.Spacer',
        'Ext.Label',
        'Ext.Button',
        'Ext.Toolbar'
    ],

    config: {
        id: 'About',
        scrollable: 'vertical',
        items: [
            {
                xtype: 'image',
                height: 136,
                margin: '5 0 0 0',
                src: 'resources/images/dnlogo.png'
            },
            {
                xtype: 'panel',
                margin: '5 0 0 0',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'spacer',
                        flex: 1
                    },
                    {
                        xtype: 'label',
                        html: 'Vilakis Innovations',
                        cls : 'aboutViewLabelCls'
                    },
                    {
                        xtype: 'spacer',
                        flex: 1
                    }
                ]
            },
            {
                xtype: 'container',
                height: 57,
                margin: '5 0 0 0',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'button',
                        cls: 'roundedButton',
                        height: 40,
                        margin: '0 0 0 10',
                        style: 'background-color:#32AFE7;color:White;',
                        ui: 'plain',
                        text: 'Email'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        cls: 'roundedButton',
                        height: 40,
                        margin: '0 10 0 0',
                        style: 'background-color:#32AFE7;color:White;',
                        ui: 'plain',
                        text: 'Website'
                    }
                ]
            },
            {
                xtype: 'panel',
                itemId: 'AboutUsPanel',
                items: [
                    {
                        xtype: 'label',
                        html: 'Vilakis innovations is a mobile application development company focused on providing affordable mobile applications using the latest innovative technologies for application development that meets international standards. This ensures that all our products are updated with the latest in  Development and Design Guidelines. We present to you Digital Noticeboard  Application.',
                        cls : 'aboutViewLabelVilakisDescriptionCls'
                    },
                    {
                        xtype: 'panel',
                        margin: '5 0 0 0',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'spacer',
                                flex: 1
                            },
                            {
                                xtype: 'label',
                                html: 'Digital Noticeboard',
                                cls : 'aboutViewLabelDigitalNoticeBoardCls'
                            },
                            {
                                xtype: 'spacer',
                                flex: 1
                            }
                        ]
                    },
                    {
                        xtype: 'label',
                        html: 'This application is your mobile noticeboard for information on current  social, business, religious, and all other activities. Keep current and up  to date! Event Organizers, get your event promoted to the thousands of  usres of this multimedia product in a second!!! Display your notice details,  digital image, audio and video adverts. Post your programme outline and  agenda for business events, seminars and workshops. Send push notification to potential attendees and RSVP patrons. Interact live with your patrons and keep them up to date with your event,  obtain feedback from your customers. live on Digital Noticeboard. Companies  advertising products and promotions, there is a place for you on Digital  Noticeboard Expose products and services to thousands of users with our  effective features designed specifically for advertisements. Download our  application now@ its FREE to download on the app stores. Do not miss out on  this novel multimedia product!!!',
                        cls : 'aboutViewLabelDigitalDescriptionCls'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                scrollable: 'vertical',
                title: 'About',
                items: [
                    {
                        xtype: 'button',
                        html: 'Back',
                        itemId: 'AboutBack',
                        ui: 'plain',
                        iconCls: 'previousArrowIcon'
                    },
                    {
                        xtype: 'spacer'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onAboutBackTap',
                event: 'tap',
                delegate: '#AboutBack'
            }
        ]
    },

    onAboutBackTap: function(button, e, eOpts) {
        Ext.getCmp('About').hide();
        Ext.getCmp('Settings').show();
    }

});