/*
 * File: app/view/Account.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DNB.view.Account', {
    extend: 'Ext.Container',
    alias: 'widget.account',

    requires: [
        'Ext.Panel',
        'Ext.Spacer',
        'Ext.Img',
        'Ext.Button',
        'Ext.Toolbar',
        'Ext.Label',
        'Ext.field.TextArea',
        'DNB.view.ChangePassword',
        'DNB.view.ChangEmail'
    ],

    config: {
        id: 'Account',
        layout: 'vbox',
        scrollable: 'vertical',
        items: [
            {
                xtype: 'panel',
                margin: '20% 0 0 0',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'spacer',
                        flex: 1
                    },
                    {
                        xtype: 'image',
                        cls: 'circleImage',
                        id: 'UserProfileImage',
                        itemId: 'myimg10',
                        margin: 0,
                        style: '   width: 120px;     height: 120px;   border-radius: 100%;     border: solid 3px #32AFE7;     padding: 2px;     box-shadow: #eeeeee 0px 0px 0px 6px inset;'
                    },
                    {
                        xtype: 'spacer',
                        flex: 1
                    }
                ]
            },
            {
                xtype: 'button',
                height: '',
                html: '<a href="#" style="color:#32AFE7;">Upload</a>',
                itemId: 'UploadImage',
                margin: '10 0 20% 0',
                style: 'color:#32AFE7;     text-transform: uppercase;     font-weight: bold;',
                ui: 'plain',
                text: 'UploadProfileImage'
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Account Settings',
                items: [
                    {
                        xtype: 'button',
                        html: 'Back',
                        itemId: 'Back',
                        ui: 'plain',
                        iconCls: 'previousArrowIcon'
                    },
                    {
                        xtype: 'spacer'
                    }
                ]
            },
            {
                xtype: 'panel',
                cls: 'default-botom-border',
                style: 'height:42px;',
                layout: 'hbox',
                id:'accountUserNamePanel',
                items: [
                    {
                        xtype: 'panel',
                        flex: 1,
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'panel',
                                flex: 1,
                                hidden: true,
                                id: 'UserNamePanel',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        flex: 1,
                                        id: 'UserName',
                                        clearIcon: false,
                                        labelWidth: '50%',
                                        placeHolder: 'User Name'
                                        // ,
                                     //    listeners: {
                                     //    focus: function(comp, e, eopts) {  
                                     //       var ost = 315;
                                     //        Ext.getCmp('Account').getScrollable().getScroller().scrollTo(0, ost);
                                     //    }
                                     // }
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                id: 'UserNameLabelPanel',
                                width: '100%',
                                layout: 'fit',
                                items: [
                                    {
                                        xtype: 'label',
                                        id: 'UserNameLabel',
                                        style: 'background-color:white;color:gray;text-align:left;'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        style: 'background-color:white;',
                        items: [
                            {
                                xtype: 'button',
                                html: '<img style="margin-right: 6px;margin-top:11px;" width="12px"src="resources/images/acc_edit.png" />',
                                itemId: 'UpdateUserName',
                                ui: 'plain'
                            },
                            {
                                xtype: 'label',
                                id: 'UsernameOnUserProfile'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                height: 80,
                cls: 'default-botom-border',
                //style: 'border-bottom:1px solid gray;',
                layout: 'hbox',
                id:'DescriptionPanel',
                items: [
                    {
                        xtype: 'panel',
                        flex: 1,
                        padding: 5,
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'panel',
                                hidden: true,
                                id: 'UserMessagePanel',
                                
                                items: [
                                    {
                                        xtype: 'textareafield',
                                        height: '100%',
                                        cls: 'usermessage',
                                        hidden: false,
                                        id: 'UserMessage',
                                        itemId: 'mytextarea2',
                                        clearIcon: false
                                    //     ,
                                    //     listeners: {
                                    //     focus: function(comp, e, eopts) {
                                    //      var ost = 350;
                                    //         Ext.getCmp('Account').getScrollable().getScroller().scrollTo(0, ost);
                                    //     }
                                    // }
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                id: 'UserMessageLabelPanel',
                                items: [
                                    {
                                        xtype: 'label',
                                        height: '100%',
                                        id: 'UserMessageLabel',
                                        padding: '5 5 5 20',
                                        style: 'background-color:white;color:gray;text-align:left;line-height:70px;font-size:15px;',
                                        width: '100%'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        style: 'background-color:white;',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'button',
                                html: '<img width="12px"src="resources/images/acc_edit.png" />',
                                itemId: 'UpdateUserMessage',
                                style: 'background-color:white;margin-top:19px;',
                                ui: 'plain'
                            },
                            {
                                xtype: 'label',
                                id: 'UserMessageLength',
                                itemId: 'UserMessageLength',
                                style: 'background-color:white;color:#32AFE7;text-align:right;  padding-right:12px;margin-top:7px;'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'button',
                cls: 'x-button-border-bottom default-botom-border',
                id: 'ChangeEmailAddress',
                itemId: 'ChangeEmailAddress',
                style: 'background-color:white;color:#32AFE7;',
                ui: 'plain',
                labelCls: 'x-button-label x-button-left',
                text: 'Change Email Address'
            },
            {
                xtype: 'button',
                id: 'ChangePasswordButton',
                cls: 'default-botom-border',
                itemId: 'ChangePassword',
                style: 'background-color:white;color:#32AFE7;',
                ui: 'plain',
                labelCls: 'x-button-label x-button-left',
                text: 'Change Password'
            }
        ],
        listeners: [
            {
                fn: 'onUserProfileImageLoad',
                event: 'load',
                delegate: '#UserProfileImage'
            },
            {
                fn: 'onUserProfileImageError',
                event: 'error',
                delegate: '#UserProfileImage'
            },
            {
                fn: 'onUploadImageButtonTap',
                event: 'tap',
                delegate: '#UploadImage'
            },
            {
                fn: 'onBackTap',
                event: 'tap',
                delegate: '#Back'
            },
            {
                fn: 'onUpdateUserNameTap',
                event: 'tap',
                delegate: '#UpdateUserName'
            },
            {
                fn: 'onUserMessageKeyup',
                event: 'keyup',
                delegate: '#UserMessage'
            },
            {
                fn: 'onUpdateUserMessageTap',
                event: 'tap',
                delegate: '#UpdateUserMessage'
            }
        ]
    },

    onUserProfileImageLoad: function(image, e, eOpts) {
        Ext.Viewport.setMasked(false);
    },

    onUserProfileImageError: function(image, e, eOpts) {
        Ext.Viewport.setMasked(false);
    },

    onUploadImageButtonTap: function(button, e, eOpts) {

        var imageURI=null;
        // window.imagePicker.getPictures(function success(results) {
        //     for (var i = 0; i < results.length; i++) {
        //         console.log('Image URI: ' + results[i]);
        //         imageURI = results[i];
        //     }
        //     var fileName = imageURI.substr(imageURI.lastIndexOf('/') + 1);
        //     var fileExtension='.'+fileName.split('.')[1];
        //     // alert(fileExtension);
        //         if(promotionUploadSetting.image.formate.indexOf(':'+fileExtension+':')<0){
        //             Ext.getCmp('UserProfileImage').setSrc('resources/images/addimage.PNG');
        //             Ext.Msg.alert('','Only .jpg & .png type files can be uploaded.');
        //             return;
        //         }
        //         // else if(promotionUploadSetting.image.size<fileSize)
        //         // {
        //         //     Ext.getCmp('UserProfileImage').setSrc('resources/images/addimage.PNG');
        //         //     Ext.Msg.alert('','File size should not be greater than '+promotionUploadSetting.image.size+' kb');
        //         //     return;
        //         // }
        //         Ext.getCmp('UserProfileImage').setSrc(imageURI);
        //         var ft = new FileTransfer();

        //         var    path = imageURI;
        //         var    name =imageURI.substr(imageURI.lastIndexOf('/') + 1);// mediaFile.name;//mediaFile.fullPath

        //         var options = new FileUploadOptions();
        //         options.fileKey = "img";
        //         options.fileName = imageURI.substr(imageURI.lastIndexOf('/') + 1);
        //         options.mimeType =  "image/jpeg";

        //         var params = {};
        //         params.method= 'userProfileImage';
        //         params.img = name;
        //         params.user_id = localStorage.getItem('userid');
        //         options.params = params;
        //         //localStorage.setItem('image',name);

        //         ft.upload(path,
        //                   webserviceURL+"users/update_profile_img.json",
        //                   function(result) {
        //                       Ext.Msg.alert('Image uploaded successfully.');
        //                       var img=Ext.decode(result.response);
        //                       //alert('IMAGE URL:'+img.response_data.User.img);
        //                       localStorage.setItem('image',img.response_data.User.img);
        //                       //console.log(result.bytesSent + ' bytes sent');
        //                   },
        //                   function(error) {Ext.Msg.alert('error');
        //                                    console.log('Error uploading file ' + path + ': ' + error.code);
        //                                   },
        //                   options);

            
        // }, function error(error) {
        //     console.log('Error: ' + error);
        //     Ext.Msg.alert('','Failed because: ' + error);
        // }, {
        //     maximumImagesCount: 1,
        //     width: 800,
        //     height: 400
        // });

        navigator.camera.getPicture(function success(results) {

            imageURI = results;
            var fileName = imageURI.substr(imageURI.lastIndexOf('/') + 1);
            var fileExtension='.'+fileName.split('.')[1];
            // alert(fileExtension);
                // if(promotionUploadSetting.image.formate.indexOf(':'+fileExtension+':')<0){
                //     Ext.getCmp('UserProfileImage').setSrc('resources/images/addimage.PNG');
                //     Ext.Msg.alert('','Only .jpg & .png type files can be uploaded.');
                //     return;
                // }
                // else if(promotionUploadSetting.image.size<fileSize)
                // {
                //     Ext.getCmp('UserProfileImage').setSrc('resources/images/addimage.PNG');
                //     Ext.Msg.alert('','File size should not be greater than '+promotionUploadSetting.image.size+' kb');
                //     return;
                // }
                Ext.getCmp('UserProfileImage').setSrc(imageURI);
                var ft = new FileTransfer();

                var    path = imageURI;
                var    name =imageURI.substr(imageURI.lastIndexOf('/') + 1);// mediaFile.name;//mediaFile.fullPath

                var options = new FileUploadOptions();
                options.fileKey = "img";
                options.fileName = imageURI.substr(imageURI.lastIndexOf('/') + 1);
                options.mimeType =  "image/jpeg";

                var params = {};
                params.method= 'userProfileImage';
                params.img = name;
                params.user_id = localStorage.getItem('userid');
                options.params = params;
                //localStorage.setItem('image',name);

                ft.upload(path,
                          webserviceURL+"users/update_profile_img.json",
                          function(result) {
                              Ext.Msg.alert('Image uploaded successfully.');
                              var img=Ext.decode(result.response);
                              //alert('IMAGE URL:'+img.response_data.User.img);
                              localStorage.setItem('image',img.response_data.User.img);
                              //console.log(result.bytesSent + ' bytes sent');
                          },
                          function(error) {Ext.Msg.alert('error');
                                           console.log('Error uploading file ' + path + ': ' + error.code);
                                          },
                          options);

            

        }, function error(error) {
            console.log('Error: ' + error);
            Ext.Msg.alert('','Failed because: ' + error);
        },
        {
            destinationType: Camera.DestinationType.FILE_URI,
            sourceType: Camera.PictureSourceType.PHOTOLIBRARY,
            quality: 25
        });


        
    },

    onBackTap: function(button, e, eOpts) {
                Ext.getCmp('Account').hide();
                Ext.getCmp('Settings').show();
    },

    onUpdateUserNameTap: function(button, e, eOpts) {
        if(Ext.getCmp('UserNameLabelPanel').getHidden()==false){
            Ext.getCmp('UserNamePanel').show();
            Ext.getCmp('UserName').focus();
            Ext.getCmp('UserNameLabelPanel').hide();
        }
        else{
            var firstname='';//Ext.getCmp('UserFirstName').getValue();
            var lastname='';//Ext.getCmp('UserLastName').getValue();
            var UserName=Ext.getCmp('UserName').getValue();

            if(UserName==''){
                Ext.Msg.alert('','User name is mandatory!');
            }
            else{
                Ext.Viewport.setMasked({xtype:'loadmask',message:'Updating..'});
                Ext.Ajax.request({
                    url:DNB.util.Common.api.changename,
                    method:'POST',
                    params :  {
                        fname:firstname,lname:lastname,username:UserName,
                        uid:localStorage.getItem('userid')
                    },
                    success:function(res,options){
                        Ext.Viewport.setMasked(false);
                        localStorage.setItem('username',UserName);
                        console.log('success:'+res.responseText);
                        var res=Ext.decode(res.responseText).Result;
                        if(res.status){
                            // Ext.Msg.alert('',res.message);
                            Ext.Msg.alert('','Updated successfully.');
                            Ext.getCmp('UserNameLabel').setHtml(UserName);//firstname+' '+lastname);
                            Ext.getCmp('UserNamePanel').hide();
                            Ext.getCmp('UserNameLabelPanel').show();
                        }
                    },
                    failure:function(res,options){
                        Ext.Viewport.setMasked(false);
                        Ext.Msg.alert('','Updation failed');
                    }
                });
            }
        }
    },

    onUserMessageKeyup: function(textfield, e, eOpts) {
        //console.log(textfield.getValue());

        if(parseInt(textfield.getValue().length)==150){
            Ext.Msg.alert('','You are allowed to type only 150 characters!');
            return false;
        }
        if(textfield.getValue().length>150){
            textfield.setValue(textfield.getValue().substr(0,150));
        }
        Ext.getCmp('UserMessageLength').setHtml(150 - parseInt(textfield.getValue().length));
    },

    onUpdateUserMessageTap: function(button, e, eOpts) {
        //alert(Ext.getCmp('UserMessageLabelPanel').isHidden());
        if(isUserMessagePanelHidden){//} Ext.getCmp('UserMessageLabelPanel').isHidden()==false){
            isUserMessagePanelHidden=false;
            Ext.getCmp('UserMessagePanel').show();
            Ext.getCmp('UserMessageLabel').setHtml(localStorage.getItem('usermessage'));
            Ext.getCmp('UserMessage').focus();
            Ext.getCmp('UserMessageLabelPanel').hide();
        }
        else{
            var userMessage=Ext.getCmp('UserMessage').getValue();

            if(userMessage==''){
                Ext.Msg.alert('','Message is mandatory!');
            }
            else{
                Ext.Viewport.setMasked({xtype:'loadmask',message:'Updating..'});
                Ext.Ajax.request({
                    url:DNB.util.Common.api.addStatusMessage,
                    method:'POST',
                    params :  {
                        mgs:userMessage,uid:localStorage.getItem('userid')
                    },
                    success:function(res,options){
                        Ext.Viewport.setMasked(false);
                        //alert('success:'+res.responseText);
                        var res=Ext.decode(res.responseText).Result;
                        //alert(res.message);
                        if(res.status){
                            Ext.Msg.alert('','Updated successfully.');
                            isUserMessagePanelHidden=true;
                            Ext.getCmp('UserMessagePanel').hide();
                            Ext.getCmp('UserMessageLabelPanel').show();
                            Ext.getCmp('UserMessageLabel').setHtml(userMessage);
                            localStorage.setItem('usermessage',userMessage);
                        }
                    },
                    failure:function(res,options){
                        Ext.Viewport.setMasked(false);
                        Ext.Msg.alert('failure'+res.responseText);
                    }
                });
            }
        }
    }

});