/*
 * File: app/view/AddEvent.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DNB.view.AddEvent', {
    extend: 'Ext.Container',
    alias: 'widget.addevent',

    requires: [
        'Ext.Img',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.Button',
        'Ext.Label',
        'Ext.picker.Slot',
        'Ext.field.Toggle',
        'Ext.field.Email',
        'Ext.field.TextArea',
        'Ext.Toolbar'
    ],

    config: {
        id: 'AddEvent',
        scrollable: 'vertical',
        items: [
            {
                xtype: 'image',
                height: 100,
                html: 'Add Image',
                id: 'EventImageOnEventPage',
                itemId: 'myimg9'
            },
            {
                xtype: 'textfield',
                id: 'EventNameOnEventPage',
                style: 'border-bottom:1px solid black;',
                placeHolder: 'Notice Name'
            },
            {
                xtype: 'textfield',
                id: 'EventLocationOnEventPage',
                style: 'border-bottom:1px solid black;',
                placeHolder: 'Notice Location'
            },
            {
                xtype: 'datepickerfield',
                id: 'EventStartDate',
                style: 'border-bottom:1px solid black;',
                label: 'Start Date',
                labelWidth: '50%',
                placeHolder: 'mm/dd/yyyy'
            },
            {
                xtype: 'datepickerfield',
                id: 'EventEndDate',
                style: 'border-bottom:1px solid black;',
                label: 'End Date',
                labelWidth: '50%',
                placeHolder: 'mm/dd/yyyy'
            },
            {
                xtype: 'panel',
                style: 'background-color:white;',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'label',
                        flex: 1,
                        html: 'Time From',
                        padding: '5 0 0 12'
                    },
                    {
                        xtype: 'button',
                        height: 45,
                        html: '<img width="32px" height="32px" src="resources/images/plus-icon.png">',
                        itemId: 'TimeFromButton',
                        padding: '5 2 2 2',
                        style: 'background-color:white',
                        ui: 'plain'
                    }
                ]
            },
            {
                xtype: 'picker',
                hidden: true,
                id: 'EventTimeOnEventPage',
                style: 'border-bottom:1px solid black;',
                slots: [
                    {
                        xtype: 'pickerslot',
                        data: [
                            {
                                text: '1',
                                value: 1
                            },
                            {
                                text: '2',
                                value: 2
                            },
                            {
                                text: '3',
                                value: 3
                            },
                            {
                                text: '4',
                                value: 4
                            },
                            {
                                text: '5',
                                value: 5
                            },
                            {
                                text: '6',
                                value: 6
                            },
                            {
                                text: '7',
                                value: 7
                            },
                            {
                                text: '8',
                                value: 8
                            },
                            {
                                text: '9',
                                value: 9
                            },
                            {
                                text: '10',
                                value: 10
                            },
                            {
                                text: '11',
                                value: 11
                            },
                            {
                                text: '12',
                                value: 12
                            }
                        ],
                        name: 'Hours'
                    },
                    {
                        xtype: 'pickerslot',
                        data: [
                            {
                                text: '1',
                                value: 1
                            },
                            {
                                text: '2',
                                value: 2
                            },
                            {
                                text: '3',
                                value: 3
                            },
                            {
                                text: '4',
                                value: 4
                            },
                            {
                                text: '5',
                                value: 5
                            },
                            {
                                text: '6',
                                value: 6
                            },
                            {
                                text: '7',
                                value: 7
                            },
                            {
                                text: '8',
                                value: 8
                            },
                            {
                                text: '9',
                                value: 9
                            },
                            {
                                text: '10',
                                value: 10
                            },
                            {
                                text: '11',
                                value: 11
                            },
                            {
                                text: '12',
                                value: 12
                            },
                            {
                                text: '13',
                                value: 13
                            },
                            {
                                text: '14',
                                value: 14
                            },
                            {
                                text: '15',
                                value: 15
                            },
                            {
                                text: '16',
                                value: 16
                            },
                            {
                                text: '17',
                                value: 17
                            },
                            {
                                text: '18',
                                value: 18
                            },
                            {
                                text: '19',
                                value: 19
                            },
                            {
                                text: '20',
                                value: 20
                            },
                            {
                                text: '21',
                                value: 21
                            },
                            {
                                text: '22',
                                value: 22
                            },
                            {
                                text: '23',
                                value: 23
                            },
                            {
                                text: '24',
                                value: 24
                            },
                            {
                                text: '25',
                                value: 25
                            },
                            {
                                text: '26',
                                value: 26
                            },
                            {
                                text: '27',
                                value: 27
                            },
                            {
                                text: '28',
                                value: 28
                            },
                            {
                                text: '29',
                                value: 29
                            },
                            {
                                text: '30',
                                value: 30
                            },
                            {
                                text: '31',
                                value: 31
                            },
                            {
                                text: '32',
                                value: 32
                            },
                            {
                                text: '33',
                                value: 33
                            },
                            {
                                text: '34',
                                value: 34
                            },
                            {
                                text: '35',
                                value: 35
                            },
                            {
                                text: '36',
                                value: 36
                            },
                            {
                                text: '37',
                                value: 37
                            },
                            {
                                text: '38',
                                value: 38
                            },
                            {
                                text: '39',
                                value: 39
                            },
                            {
                                text: '40',
                                value: 40
                            },
                            {
                                text: '41',
                                value: 41
                            },
                            {
                                text: '42',
                                value: 42
                            },
                            {
                                text: '43',
                                value: 43
                            },
                            {
                                text: '44',
                                value: 44
                            },
                            {
                                text: '45',
                                value: 45
                            },
                            {
                                text: '46',
                                value: 46
                            },
                            {
                                text: '47',
                                value: 47
                            },
                            {
                                text: '48',
                                value: 48
                            },
                            {
                                text: '49',
                                value: 49
                            },
                            {
                                text: '50',
                                value: 50
                            },
                            {
                                text: '51',
                                value: 51
                            },
                            {
                                text: '52',
                                value: 52
                            },
                            {
                                text: '53',
                                value: 53
                            },
                            {
                                text: '54',
                                value: 54
                            },
                            {
                                text: '55',
                                value: 55
                            },
                            {
                                text: '56',
                                value: 56
                            },
                            {
                                text: '57',
                                value: 57
                            },
                            {
                                text: '58',
                                value: 58
                            },
                            {
                                text: '59',
                                value: 59
                            }
                        ],
                        name: 'Minutes'
                    },
                    {
                        xtype: 'pickerslot',
                        data: [
                            {
                                text: 'AM',
                                value: 'AM'
                            },
                            {
                                text: 'PM',
                                value: 'PM'
                            }
                        ],
                        align: 'center',
                        name: 'AMPM'
                    }
                ]
            },
            {
                xtype: 'panel',
                style: 'background-color:white;',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'label',
                        flex: 1,
                        hidden: true,
                        html: 'Video Link',
                        padding: '5 0 0 12'
                    },
                    {
                        xtype: 'button',
                        height: 45,
                        hidden: true,
                        html: '<img width="32px" height="32px" src="resources/images/plus-icon.png">',
                        itemId: 'UploadNoticeVideo',
                        padding: '5 2 2 2',
                        style: 'background-color:white',
                        ui: 'plain'
                    },
                    {
                        xtype: 'textfield',
                        id: 'VideoLinkUrls',
                        label: 'Video Link',
                        labelWidth: '40%'
                    }
                ]
            },
            {
                xtype: 'panel',
                style: 'background-color:white;',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'label',
                        flex: 1,
                        html: 'Audio Clip',
                        padding: '5 0 0 12'
                    },
                    {
                        xtype: 'button',
                        height: 45,
                        html: '<img width="32px" height="32px" src="resources/images/plus-icon.png">',
                        itemId: 'UploadNoticeAudio',
                        padding: '5 2 2 2',
                        style: 'background-color:white',
                        ui: 'plain'
                    }
                ]
            },
            {
                xtype: 'panel',
                style: 'background-color:white;',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'label',
                        flex: 1,
                        html: 'Pictures',
                        padding: '5 0 0 12'
                    },
                    {
                        xtype: 'button',
                        height: 45,
                        html: '<img width="32px" height="32px" src="resources/images/plus-icon.png">',
                        itemId: 'UploadNoticeImage',
                        padding: '5 2 2 2',
                        style: 'background-color:white',
                        ui: 'plain'
                    }
                ]
            },
            {
                xtype: 'panel',
                style: 'background-color:white;',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'label',
                        flex: 1,
                        html: 'Display On',
                        padding: '5 0 0 12'
                    },
                    {
                        xtype: 'button',
                        height: 45,
                        html: '<img width="32px" height="32px" src="resources/images/plus-icon.png">',
                        id: 'EventCategoryButton',
                        itemId: 'SelectCategory',
                        padding: '5 2 2 2',
                        style: 'background-color:white',
                        ui: 'plain'
                    }
                ]
            },
            {
                xtype: 'selectfield',
                id: 'PayStatus',
                style: 'border-bottom:1px solid black;',
                label: 'Pay Status',
                labelWidth: '40%',
                placeHolder: '',
                store: 'EventPayStatusStore'
            },
            {
                xtype: 'togglefield',
                id: 'EventHotFive',
                padding: 5,
                label: 'Hot Five List+',
                labelWidth: '70%'
            },
            {
                xtype: 'textfield',
                id: 'EventPhone',
                style: 'border-bottom:1px solid black;',
                placeHolder: 'Phone'
            },
            {
                xtype: 'emailfield',
                id: 'EventEmail',
                style: 'border-bottom:1px solid black;',
                placeHolder: 'Email'
            },
            {
                xtype: 'textfield',
                id: 'EventWebsite',
                style: 'border-bottom:1px solid black;',
                placeHolder: 'Website'
            },
            {
                xtype: 'togglefield',
                id: 'EventComments',
                style: 'border-bottom:1px solid black;',
                label: 'Comments',
                labelWidth: '67%'
            },
            {
                xtype: 'textareafield',
                id: 'EventDescription',
                placeHolder: 'Description'
            },
            {
                xtype: 'button',
                height: 50,
                itemId: 'EventSubmit',
                style: 'background-color:#32AFE7;color:White;',
                ui: 'plain',
                text: 'Submit'
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        html: 'Back',
                        itemId: 'Back',
                        ui: 'plain',
                        text: 'Back'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onEventImageOnEventPageTap',
                event: 'tap',
                delegate: '#EventImageOnEventPage'
            },
            {
                fn: 'onTimeFromButtonTap',
                event: 'tap',
                delegate: '#TimeFromButton'
            },
            {
                fn: 'onUploadNoticeVideoTap',
                event: 'tap',
                delegate: '#UploadNoticeVideo'
            },
            {
                fn: 'onUploadNoticeAudioTap',
                event: 'tap',
                delegate: '#UploadNoticeAudio'
            },
            {
                fn: 'onUploadNoticeImageTap',
                event: 'tap',
                delegate: '#UploadNoticeImage'
            },
            {
                fn: 'onSelectCategoryTap1',
                event: 'tap',
                delegate: '#EventCategoryButton'
            },
            {
                fn: 'onEventSubmitTap',
                event: 'tap',
                delegate: '#EventSubmit'
            },
            {
                fn: 'onBackTap',
                event: 'tap',
                delegate: '#Back'
            }
        ]
    },

    onEventImageOnEventPageTap: function(image, e, eOpts) {
        navigator.camera.getPicture(
            function cameraSuccess(imageURI){


                noticeImageBannerFILEURI=imageURI;


            },

            function cameraError(message) {
                alert('Failed because: ' + message);
            }
            ,{quality:50,
              mediaType:Camera.MediaType.ALLMEDIA,
              sourceType:Camera.PictureSourceType.SAVEDPHOTOALBUM,
              destinationType:Camera.DestinationType.FILE_URI} );

    },

    onTimeFromButtonTap: function(button, e, eOpts) {
        Ext.getCmp('EventTimeOnEventPage').show();
    },

    onUploadNoticeVideoTap: function(button, e, eOpts) {

    },

    onUploadNoticeAudioTap: function(button, e, eOpts) {
        window.plugins.iOSAudioPicker.getAudio(function(res){
                    //noticeAudioFILEURI=res[0].exportedurl;
                    //alert('res.length:'+res.length);
                    if(res.length>0){
                                                       var tempAudio=[];
                        for(var i=0;i<res.length;i++){
                            //noticeAudioFILEURI +=','+res[i].exportedurl;
                                       tempAudio.push(res[i].exportedurl);
                        }
                        //alert(noticeAudioFILEURI);
                        //f(noticeAudioFILEURI.length>1)
                        //    noticeAudioFILEURI=noticeAudioFILEURI.substr(1);
                       //alert(noticeAudioFILEURI);
                                    noticeAudioFILEURI=tempAudio.join(',');
                alert('Audio files selected successfully');
                    }
                },
                        function(){
                            alert('Unable to select audio file.');
                        },true,true);
    },

    onUploadNoticeImageTap: function(button, e, eOpts) {
        window.imagePicker.getPictures(
            function(results) {
                var img=[];
                for (var i = 0; i < results.length; i++) {
                    img.push(results[i]);
                    console.log('Image URI: ' + results[i]);
                }
                noticeImageFILEURI=img.join(',');
            }, function (error) {
                console.log('Error: ' + error);
            }, {
                maximumImagesCount: 10,
                width: 800
            }
        );
        return;
        navigator.camera.getPicture(
            function cameraSuccess(imageURI){


                noticeImageFILEURI=imageURI;


            },

            function cameraError(message) {
                alert('Failed because: ' + message);
            }
            ,{quality:50,
              mediaType:Camera.MediaType.ALLMEDIA,
              sourceType:Camera.PictureSourceType.SAVEDPHOTOALBUM,
              destinationType:Camera.DestinationType.FILE_URI} );

    },

    onSelectCategoryTap1: function(button, e, eOpts) {
        selectedCategoryIDsToAdd='';
        if(Ext.getCmp('CategoryMultiSelect'))
            Ext.getCmp('CategoryMultiSelect').show();
        else
            Ext.Viewport.add({xtype:'categorymultiselect'}).show();
        Ext.getStore('EventCategoryMultiSelectStore').setData(categoryDataToAdd);

    },

    onEventSubmitTap: function(button, e, eOpts) {
        var eventName=Ext.getCmp('EventNameOnEventPage').getValue();
                var eventLocation=Ext.getCmp('EventLocationOnEventPage').getValue();
                var eventStartDate=Ext.getCmp('EventStartDate').getValue();
                var eventEndDate=Ext.getCmp('EventEndDate').getValue();
                var eventTime=Ext.getCmp('EventTimeOnEventPage').getValue();
                var eventVideoLink=Ext.getCmp('VideoLinkUrls').getValue();
                var eventCategory=selectedCategoryIDsToAdd;// Ext.getCmp('EventCategory').getValue();
                var payStatus=Ext.getCmp('PayStatus').getValue();
                var eventHotFive=Ext.getCmp('EventHotFive').getValue();
                var eventPhone=Ext.getCmp('EventPhone').getValue();
                var eventEmail=Ext.getCmp('EventEmail').getValue();
                var eventWebsite=Ext.getCmp('EventWebsite').getValue();
                var eventComments=Ext.getCmp('EventComments').getValue();
                var eventDescription=Ext.getCmp('EventDescription').getValue();
        alert(eventTime+'\n'+eventStartDate);
        return;
                var ft = new FileTransfer();
                        var    path = [];

                       //path.push(noticeAudioFILEURI);
                           if(noticeImageBannerFILEURI.length>0)
                              path.push(noticeImageBannerFILEURI);


                   if(noticeImageFILEURI.length>0)
                   path.push(noticeImageFILEURI);

                           path.push(';');
                   if(noticeAudioFILEURI.length>0)
                    path.push(noticeAudioFILEURI);
                        //alert(noticeImageFILEURI);
                        //alert('Audio URLs:'+noticeAudioFILEURI);
                        //alert(noticeImageBannerFILEURI);
                        var uploadFileUrls=path.join(',');
                        //alert('urls :'+uploadFileUrls);
                         var  name ='';//fileURL.substr(fileURL.lastIndexOf('/') + 1);// mediaFile.name;//mediaFile.fullPath
                         var options = new FileUploadOptions();
                                   options.fileKey = "image";
                                   options.fileName = '';//promotionImageFILEURI.substr(promotionImageFILEURI.lastIndexOf('/') + 1);
                                   options.mimeType =  "image/jpeg";
                                   var params = {};
                           params.method ="notice";// [1,2];           params.value1 = "test";
                           params.value2 = "param";
                           params.title = eventName;
                           params.description = eventDescription;
                           params.notice_type = "paid";
                           params.venu_detail = eventLocation;
                           params.date = "2015-04-25";
                           params.time_from = "11:00AM";
                           params.time_to = "1:00PM";
                           params.hot_five = eventHotFive;
                           params.duration = "2";
                           params.start_date = "2015-04-25";
                           params.end_date = "2015-04-27";
                           params.extra = "event extra data goes to here";
                           params.price = "22";
                           params.website = eventWebsite;
                           params.payment_status = "1";
                           params.user_id = "10";
                           params.categorys =eventCategory;// "3,4";

                           options.params = params;
                           alert('options:'+uploadFileUrls);
                          ft.upload(uploadFileUrls,//    path.join(','),
                          webserviceURL+"Notices/add_notice.json",
                          function(result) {
                               alert('UPLOADED successfully');
                               alert('IMAGE URL:'+Ext.encode(result));
                               alert('IMAGE URL:'+result.response.response_data.URL);
                               console.log('Upload success: ' + result);
                                            },
                                             function(error) {alert('error');
                                             console.log('Error uploading file ' + path + ': ' + error.code);
                                             },
                                             options);
                   return;

        Ext.Ajax.request({
            url:'http://192.169.199.42/DNB/DNB_admin/Notices/add_notice.json',
            method:'POST',
            params: {
                flyer : 'demo.jpg',
                title :  eventName,
                description :  eventDescription,
                notice_type : 'free',
                categorys : [1],
                venu_detail : eventLocation,
                time_from : '11:20:00',
                time_to:  '11:20:00',
                hot_five : eventHotFive,
                duration : '2',
                start_date  : '2015-05-18',
                end_date : '2015-05-18',
                extra:  'eventDescription',
                price: 22,
                status: 'active',
                payment_status: '1',
                user_id:  '1'
            },
            success:function(res,options){
                alert('success:'+res.responseText);
                //var res=Ext.decode(res);
                //alert(res.response_data.message);
                Ext.getCmp('AddEvent').hide();
                Ext.getCmp('DNBView').show();
                Ext.getCmp('HomeContainer').show();
                DNB.app.getController('Events').GetNotices();
            },
            failure:function(res,options){
                alert('error:'+res.responseText);
            }

        });
    },

    onBackTap: function(button, e, eOpts) {
        Ext.getCmp('DNBView').show();
        Ext.getCmp('HomeContainer').show();
        Ext.getCmp('AddEvent').hide();
    }

});