/*
 * File: app/view/AddPromotion.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DNB.view.AddPromotion', {
    extend: 'Ext.Container',
    alias: 'widget.addpromotion',

    requires: [
        'Ext.Img',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.Button',
        'Ext.Label',
        'Ext.field.Toggle',
        'Ext.Toolbar',
        'Ext.Spacer'
    ],

    config: {
        id: 'AddPromotion',
        scrollable: 'vertical',
        items: [
            {
                xtype: 'image',
                height: 300,
                // cls : 'add-image',
                id: 'PromotionImageAdd',
                name: 'promotionImageAdd',
                itemId: 'myimg8',
                margin: 0,
                src: 'resources/images/addimage.PNG'
            },
            {
                xtype: 'textfield',
                cls: 'default-label-class default-botom-border default-top-border',
                id: 'PromotionTitle',
                margin: '',
                // padding: '0 0 0 5',
                // style: 'border-bottom:1px solid rgba(212, 212, 212, 0.48) !important;',
                clearIcon: false,
                label: 'Promotion Name',
                labelWidth: '40%'
                // ,
                // listeners: {
                //     focus: function(comp, e, eopts) {
                //         var ost = comp.element.dom.offsetTop;
                //         Ext.getCmp('AddPromotion').getScrollable().getScroller().scrollTo(0, ost);
                //     }
                // }
            },
            // {
            //     xtype: 'textfield',
            //     cls: 'default-label-class',
            //     id: 'PromotionLocation',
            //     name: 'promotionLocation',
            //     padding: '0 0 0 5',
            //     style: 'border-bottom:1px solid #cfcfcf;',
            //     clearIcon: false,
            //     label: 'Location',
            //     labelWidth: '40%'
            // },
            {
                
                html: '<div class="x-container x-field-text x-field x-label-align-left x-field-labeled default-label-class default-botom-border x-form-label-nowrap x-empty" id="PromotionLocation" style="border-bottom:1px solid rgba(212, 212, 212, 0.48) !important;">'+
                            '<div class="x-form-label" id="" style="width: 35% !important;">'+
                                '<span id="ext-element-651">Location</span>'+
                            '</div>'+
                            '<div class="x-component-outer" id="" style="padding: 0px !important;">'+
                                '<div class="x-unsized x-field-input" id="ext-input-8">'+
                                    '<input class="x-input-el x-form-field x-input-text" type="text" id="plocationField" name="locationPoint" placeholder="">'+
                                    '<div class="x-field-mask" style="display: none !important;" id=""></div>'+
                                    '<div class="x-clear-icon" id=""></div>'+
                                '</div>'+
                            '</div>'+
                        '</div>',
                
                autoComplete: true
            },
            {
                xtype: 'textfield',
                cls: 'default-label-class default-botom-border',
                id: 'PromotionLocationCity',
                // padding: '0 0 0 5',
                // style: 'border-bottom:1px solid #cccccc;',
                clearIcon: false,
                labelWidth: '40%',
                label: 'City'
                // ,
                // listeners: {
                //     focus: function(comp, e, eopts) {
                //         var ost = comp.element.dom.offsetTop;
                //         Ext.getCmp('AddPromotion').getScrollable().getScroller().scrollTo(0, ost);
                //     }
                // }
            },
            {
                xtype: 'textfield',
                cls: 'default-label-class default-botom-border',
                id: 'PromotionLocationState',
                // padding: '0 0 0 5',
                // style: 'border-bottom:1px solid #cccccc;',
                clearIcon: false,
                labelWidth: '40%',
                label: 'State'
                // ,
                // listeners: {
                //     focus: function(comp, e, eopts) {
                //         var ost = comp.element.dom.offsetTop;
                //         Ext.getCmp('AddPromotion').getScrollable().getScroller().scrollTo(0, ost);
                //     }
                // }
            },
            {
                xtype: 'textfield',
                cls: 'default-label-class default-botom-border',
                hidden: true,
                id: 'PromotionLocationCountry',
                // padding: '0 0 0 5',
                // style: 'border-bottom:1px solid gray;',
                clearIcon: false,
                labelWidth: '40%',
                label: 'Country'
            },
            {
                xtype: 'textfield',
                cls: 'default-label-class default-botom-border',
                id: 'PromotionLocationZip',
                // padding: '0 0 0 5',
                labelWidth: '40%',
                // style: 'border-bottom:1px solid #cccccc;',
                clearIcon: false,
                label: 'Zip'
                // ,
                // listeners: {
                //     focus: function(comp, e, eopts) {
                //         var ost = comp.element.dom.offsetTop;
                //         Ext.getCmp('AddPromotion').getScrollable().getScroller().scrollTo(0, ost);
                //     }
                // }
            },
            {
                xtype: 'datepickerfield',
                id: 'PromotionFromDate',
                name: 'promotionFromDate',
                cls : 'default-label-class default-botom-border',
                // style: 'border-bottom:1px solid #cfcfcf;',
                label: 'From Date',
                labelCls: 'default-label-class',
                labelWidth: '40%',
                placeHolder: '',
                picker: {
                    doneButton: {
                        ui: 'plain'
                    },
                    cancelButton: {
                        ui: 'plain'
                    }
                }
            },
            {
                xtype: 'datepickerfield',
                id: 'PromotionToDate',
                cls : 'default-label-class default-botom-border',
                labelCls: 'default-label-class',
                // style: 'border-bottom:1px solid #cfcfcf;',
                label: 'To Date',
                labelWidth: '40%',
                placeHolder: '',
                picker: {
                    doneButton: {
                        ui: 'plain'
                    },
                    cancelButton: {
                        ui: 'plain'
                    }
                }
            },
            {
                xtype: 'panel',
                // padding: '0 5 0 0',
                // style: 'background-color:white;color:gray;border-bottom:1px solid #cfcfcf;',
                cls : 'default-label-class default-botom-border addPromotionDisplayOnCls',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'label',
                        flex: 1,
                        html: 'Display On'
                        // style: 'font-weight:normal;color:gray;font-size:.8em;line-height:35px;'
                    },
                    {
                        xtype: 'button',
                        height: 45,
                        cls : 'add-promotion-add-btn-cls',
                        html: '<img width="32px" height="32px" src="resources/images/plus-icon.png">',
                        id: 'SelectCategoryButton',
                        name: 'selectCategoryButton',
                        itemId: 'SelectCategory',
                        padding: '5 2 2 2',
                        style: 'background-color:white; ',
                        ui: 'plain'
                    }
                ]
            },
            {
                xtype: 'togglefield',
                cls: 'default-label-class default-botom-border default-toggle-field-cls',
                id: 'PromotionHotFive',
                // padding: '3 2 0 0',
                // style: 'border-bottom:1px solid #cfcfcf;',
                label: 'Display On Hot Five',
                labelCls: 'default-label-class',
                labelWidth: '85%'
            },
            {
                xtype: 'panel',
                // padding: '0 5 0 0',
                // style: 'background-color:white;color:gray;border-bottom:1px solid #cfcfcf;',
                cls : 'default-label-class default-botom-border addPromotionAudioPanelCls',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'label',
                        flex: 1,
                        html: 'Audio'
                        // style: 'font-weight:normal;color:gray;font-size:.8em;line-height:35px;'
                    },
                    {
                        xtype: 'button',
                        height: 45,
                        cls : 'add-promotion-add-btn-cls',
                        html: '<img width="32px" height="32px" src="resources/images/plus-icon.png">',
                        itemId: 'UploadPromotionAudio',
                        name: 'uploadPromotionAudio',
                        padding: '5 2 2 2',
                        style: 'background-color:white',
                        ui: 'plain'
                    }
                ]
            },
            {
                xtype: 'textfield',
                cls: 'default-label-class default-botom-border',
                id: 'PromotionWebsite',
                // padding: '0 0 0 5',
                // style: 'border-bottom:1px solid #cfcfcf;',
                clearIcon: false,
                label: 'Website',
                labelWidth: '40%',
                labelCls: 'default-label-class'
                // ,
                // listeners: {
                //     focus: function(comp, e, eopts) {
                //         var ost = comp.element.dom.offsetTop;
                //         Ext.getCmp('AddPromotion').getScrollable().getScroller().scrollTo(0, ost);
                //     }
                // }
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                id: 'PromotionTitleToolbar',
                title: 'Add Promotion',
                items: [
                    {
                        xtype: 'button',
                        html: 'Back',
                        itemId: 'Back',
                        name: 'backPromotionPage',
                        ui: 'plain',
                        iconCls: 'previousArrowIcon'
                    },
                    {
                        xtype: 'spacer'
                    }
                ]
            },
             {
                xtype: 'toolbar',
                docked: 'bottom',
                id: 'NoticeTitleToolbar1',
                items: [
                    {
                        xtype: 'button',
                        height: 50,
                        itemId: 'Submit',
                        name: 'submitPromotion',
                        style: 'background-color:#32AFE7;color:White;',
                        ui: 'plain',
                        width: '100%',
                        text: 'Submit'
                    }
                ]
            }
            // ,
            // {
            //     xtype: 'button',
            //     height: 50,
            //     hidden:true,
            //     html: 'Submit',
            //     itemId: 'Submit',
            //     name: 'submitPromotion',
            //     style: 'background-color:#32AFE7;color:White;',
            //     ui: 'plain',
            //     text: 'Submit'
            // }
        ],
         listeners: [
            {
                fn: 'init',
                event: 'painted'
                // delegate: '#EventImageOnEventPage'
            }
            ]

    } ,
    init: function(){
            console.log('text working');
            var me = this;
            var locationInput = document.getElementById('plocationField');
         
            //Create new autocomplete object
            locationComplete = new google.maps.places.Autocomplete(locationInput);
         
            //Bias to users current location
            this.geolocate();
            var place;
         
            google.maps.event.addListener(locationComplete, 'place_changed', function() {
                place = locationComplete.getPlace();
                console.log(place); //address
                // console.log(place.formatted_address); //address
                // console.log(place.geometry.location.lat()); //latitude
                // console.log(place.geometry.location.lng()); //longitude
            });
        },
        geolocate: function() {
          if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
              var geolocation = new google.maps.LatLng(
                  position.coords.latitude, position.coords.longitude);
         
              locationComplete.setBounds(new google.maps.LatLngBounds(geolocation,
                  geolocation));
            });
          }
        } 
});