/*
 * File: app/view/ChangePassword.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */
Ext.define('DNB.view.ChangePassword', {
            extend: 'Ext.Container',
            alias: 'widget.changepassword',
            requires: ['Ext.Toolbar', 'Ext.Spacer', 'Ext.Button', 'Ext.Panel', 'Ext.field.Password', 'Ext.MessageBox'],
            config: {
                centered: true,
                id: 'ChangePassword',
                // style: 'background-color:white;border-radius: 4px;',
                modal: true,
                items: [{
                        xtype: 'toolbar',
                        // cls: 'popheader',
                        cls: 'transparentBG',
                        docked: 'top',
                        items: [{
                            xtype: 'spacer'
                        }, {
                            xtype: 'button',
                            html: '<div><img width="32" src="resources/images/feedbackclose.png"></div>',
                            // html: '<div><img  width="16" src="resources/images/CloseBlueIcon.JPG"></div>',
                            itemId: 'CloseChangePassword',
                            margin: '0 -5 0 0',
                            ui: 'plain'
                        }]
                    }, {
                        xtype: 'panel',
                        padding: 20,
                        style: 'background-color:#32AFE7;border-radius:5px;',
                        items: [{
                            xtype: 'panel',
                            height: 40,
                            html: '<div class="feedheading"> Change Password </div>'
                        }, {
                            xtype: 'passwordfield',
                            itemId: 'oldpassword',
                            margin: '10 0 0 0',
                            style: 'border-radius:10px;',
                            cls: 'roundfeedfiled',
                            clearIcon: false,
                            // style: 'background-color:#3F3F3F;border-bottom:1px solid black;color:white;',
                            placeHolder: 'Old Password'
                        }, {
                            xtype: 'passwordfield',
                            itemId: 'newpassword',
                            margin: '10 0 0 0',
                            style: 'border-radius:10px;',
                            cls: 'roundfeedfiled',
                            // style: 'background-color:#3F3F3F;border-bottom:1px solid black;color:white;',
                            placeHolder: 'New Password'
                        }, {
                            xtype: 'passwordfield',
                            itemId: 'newconfirmpassword',
                            margin: '10 0 0 0',
                            style: 'border-radius:10px;',
                            cls: 'roundfeedfiled',
                            // style: 'background-color:#3F3F3F;border-bottom:1px solid black;color:white;',
                            placeHolder: 'Confirm Password'
                        }, {
                            xtype: 'button',
                            height: 40,
                            margin: '10 auto',
                            style: 'background-color:white;color:#32AFE7;',
                            ui: 'plain',
                            width: 120,
                            cls: 'ChangeEmailAddressCls',
                            itemId: 'Submit',
                            ui: 'plain',
                            text: 'Submit'
                                // xtype: 'button',
                                // height: 50,
                                // itemId: 'Submit',
                                // style: 'background-color:#DCB209;',
                                // ui: 'plain',
                                // text: 'Submit'   
                        }]
                    }],
                    // {
                    //     xtype: 'panel',
                    //     html: 'Change Password',
                    //     margin: 0,
                    //     style: 'color:rgb(220, 178, 9);text-align:center;font-weight:bold;'
                    // }, 
                    // {
                    //     xtype: 'passwordfield',
                    //     itemId: 'oldpassword',
                    //     style: 'background-color:#3F3F3F;border-bottom:1px solid black;color:white;',
                    //     label: 'Old Password',
                    //     labelWidth: '60%'
                    // }, {
                    //     xtype: 'passwordfield',
                    //     itemId: 'newpassword',
                    //     style: 'background-color:#3F3F3F;border-bottom:1px solid black;color:white;',
                    //     label: 'New Password',
                    //     labelWidth: '60%'
                    // }, {
                    //     xtype: 'passwordfield',
                    //     itemId: 'newconfirmpassword',
                    //     style: 'background-color:#3F3F3F;border-bottom:1px solid black;color:white;',
                    //     label: 'Confirm Password',
                    //     labelWidth: '60%'
                    // }, {
                    //     xtype: 'button',
                    //     height: 50,
                    //     itemId: 'Submit',
                    //     style: 'background-color:#DCB209;',
                    //     ui: 'plain',
                    //     text: 'Submit'
                    // }],
                    listeners: [{
                        fn: 'onCloseChangePasswordTap',
                        event: 'tap',
                        delegate: '#CloseChangePassword'
                    }, {
                        fn: 'onMybutton74Tap',
                        event: 'tap',
                        delegate: '#Submit'
                    }]
                },
                onCloseChangePasswordTap: function(button, e, eOpts) {
                    Ext.getCmp('ChangePassword').hide();
                },
                onMybutton74Tap: function(button, e, eOpts) {
                    var ChangePassword = this;
                    // var oldpassword = ChangePassword.getComponent('oldpassword').getValue();
                    // var newpassword = ChangePassword.getComponent('newpassword').getValue();
                    // var newconfirmpassword = ChangePassword.getComponent('newconfirmpassword').getValue();

                    var oldpassword = ChangePassword.query('[itemId=oldpassword]')[0].getValue();
                    var newpassword = ChangePassword.query('[itemId=newpassword]')[0].getValue();
                    var newconfirmpassword = ChangePassword.query('[itemId=newconfirmpassword]')[0].getValue();

                    if (oldpassword == '') {
                        Ext.Msg.alert('', 'Old password is mandatory!');
                    } else if (oldpassword.length < 6) {
                        Ext.Msg.alert('', 'Old password should have minimum 6 characters!');
                    } else if (newpassword == '') {
                        Ext.Msg.alert('', 'New password should not be empty!');
                    } else if (newpassword.length < 6) {
                        Ext.Msg.alert('', 'New password should have minimum 6 characters!');
                    } else if (oldpassword == newpassword) {
                        Ext.Msg.alert('', 'Old password and New password should not be same.');
                    } else if (newconfirmpassword == '') {
                        Ext.Msg.alert('', 'Confirm password should not be empty!');
                    } else if (newpassword != newconfirmpassword) {
                        Ext.Msg.alert('', 'Confirm Password does not match! Please type again.');
                    } else {
                        Ext.Ajax.request({
                            url: DNB.util.Common.api.updateUserPassword,
                            method: 'POST',
                            params: {
                                old_pass: oldpassword,
                                new_pass: newpassword,
                                id: localStorage.getItem('userid')
                            },
                            success: function(res, options) {
                                console.log('change password:' + res.responseText);
                                var res = Ext.decode(res.responseText).Result;
                                if (res.message.indexOf('Password does not match') >= 0) {
                                    alert('', 'Please fill correct old password.');
                                } else alert('', res.message);
                                if (res.status) {
                                    Ext.getCmp('ChangePassword').hide();
                                    Ext.getCmp('Account').show();
                                }
                            },
                            failure: function(res, options) {
                                alert('', 'failure' + res.responseText);
                            }
                        });
                    }
                }
            });