/*
 * File: app/view/DNBMessage.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DNB.view.DNBMessage', {
    extend: 'Ext.Container',
    alias: 'widget.dnbmessage',

    requires: [
        'Ext.Toolbar',
        'Ext.Panel',
        'Ext.Label',
        'Ext.Button'
    ],

    config: {
        centered: true,
        height: 195,
        id: 'DNBMessage',
        width: 185,
        zIndex: 999,
        layout: 'fit',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'DNB'
            },
            {
                xtype: 'panel',
                style: 'background-color:White;color:black;',
                items: [
                    {
                        xtype: 'label',
                        centered: true,
                        itemId: 'msg',
                        padding: '0 0 0 5'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                layout: {
                    type: 'hbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'button',
                        itemId: 'OK',
                        text: 'OK'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onOKTap',
                event: 'tap',
                delegate: '#OK'
            }
        ]
    },

    onOKTap: function(button, e, eOpts) {
                Ext.getCmp('DNBMessage').hide();
    },

    setMessage: function(msg) {
        this.getItems().items[1].getItems().items[0].setHtml(msg);
    }

});