/*
 * File: app/view/EventVideos.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DNB.view.EventVideos', {
    extend: 'Ext.Container',
    alias: 'widget.eventvideos',

    requires: [
        'Ext.Panel',
        'Ext.dataview.DataView',
        'Ext.XTemplate',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'DNB.view.EventVideoPlayer'
    ],

    config: {
        id: 'EventVideos',
        items: [
            {
                xtype: 'panel',
                items: [
                    {
                        xtype: 'dataview',
                        height: 200,
                        itemId: 'EventVideosList',
                        itemTpl: Ext.create('Ext.XTemplate', 
                            '<div style="margin:10px;"><img width="32px" height="32px" src="resources/images/playvideo.png" />',
                            '    {title}',
                            '</div>',
                            {
                                GetYoutubeId: function(url) {

                                    //{[this.GetYoutubeId(values.url)]}
                                    var pageParameters = Ext.urlDecode(url.split('?')[1]);
                                    return pageParameters.v;
                                }
                            }
                        ),
                        store: 'EventVideosStore'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Notice Videos',
                items: [
                    {
                        xtype: 'button',
                        html: 'Back',
                        itemId: 'Back',
                        ui: 'plain',
                        iconCls: 'previousArrowIcon'
                    },
                    {
                        xtype: 'spacer'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onEventVideosListItemTap',
                event: 'itemtap',
                delegate: '#EventVideosList'
            },
            {
                fn: 'onBackTap',
                event: 'tap',
                delegate: '#Back'
            }
        ]
    },

    onEventVideosListItemTap: function(dataview, index, target, record, e, eOpts) {
        //open vieo
        ShowHideHomePages('EventVideoPlayerContainer');
        var youtubeurl=record.data.url;//http://www.youtube.com/embed/XGSy3_Czz8k?autoplay=1
        //1. https://www.youtube.com/watch?v=TRrL5j3MIvo
        // working :https://www.youtube.com/embed/TRrL5j3MIvo
        /*if(youtubeurl.indexOf('watch?v=')>=0){
            youtubeurl=youtubeurl.replace('watch?v=','embed/');
        }
        Ext.getCmp('EventVideoYoutubePlayer').setHtml('<iframe width="280" height="185" src="'+youtubeurl+'"> </iframe>');
        */
        var pageParameters = Ext.urlDecode(record.data.url.split('?')[1]);
        youtubeurl=pageParameters.v;
        console.log(youtubeurl);
        var embedYoutubeUrl='';
        Ext.getCmp('EventVideoYoutubePlayer').setHtml('<iframe height="480px" width="720px" class="youtube-player" type="text/html" src="http://www.youtube.com/embed/'+youtubeurl+'?modestbranding=1&showsearch=0&rel=0&theme=dark&showinfo=0&iv_load_policy=3" frameborder="0" allowfullscreen></iframe>');

    },

    onBackTap: function(button, e, eOpts) {
        ShowHideHomePages('EventDetailContainer');
    }

});