/*
 * File: app/view/EventSearch.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DNB.view.EventSearch', {
    extend: 'Ext.Container',
    alias: 'widget.eventsearch',

    requires: [
        'Ext.dataview.DataView',
        'Ext.XTemplate',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.field.Search',
        'DNB.view.CategoryOnSearch'
    ],

    config: {
        id: 'EventSearch',
        layout: 'fit',
        items: [
            {
                xtype: 'dataview',
                itemId: 'mydataview7',
                margin: '0 0 0 0',
                padding: '5 0 0 0',
                style: 'background-color:white;',
                scrollable: 'vertical',
                itemTpl: Ext.create('Ext.XTemplate', 
                    '<table class="default-botom-border" style="color:#32AFE7;font-size:14px;width: 100%;"><tr>',
                    '    <td style="width: 30%;text-align: center;padding:5px;" class="round-img"><img width=\"80px\" height=\"80px\" src=\"{[this.GetImageUrl(values.flyer)]}\" onerror=DNB.app.getController(\"Events\").GetNoImageUrl(this)></td>',
                    '    <td class="listtitle">',
                    '        <h2>{title}</h2>',
                    '        <div style="margin-top:5px;">',
                    '            <div style="float:left; margin-left: 5px;">',
                    '                <img width=\"18px\" height=\"17px\" src="resources/images/calendarInEventList-img.png" style="margin-left:2px;">',
                    '            </div>',
                    '            <div style="float:left;color:black;padding-left:5px;font-weight:400;margin-left:8px;font-family:Open Sans">{end_date}</div>',
                    '        </div><br/>',
                    '',
                    '    </td>',
                    '    ',
                    '    <td> <img width=\"14px\"  src="resources/images/arrow-img.png"> </td>',
                    '    ',
                    '    ',
                    '    </tr>',
                    '',
                    '</table>  ',
                    {
                        GetImageUrl: function(imageUrl) {
                            return imageBaseUrl+imageUrl;
                        },
                        isNoticeLike: function(isLike) {
                            if(isLike=='yes'){
                                return 'resources/images/liked.PNG';
                            }else{
                                return 'resources/images/like.png';
                            }
                        }
                    }
                ),
                store: 'NoticesSearchStore'
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        hidden: true,
                        itemId: 'ShowCategoryList',
                        ui: 'plain',
                        icon: 'list',
                        iconCls: 'list'
                    },
                    {
                        xtype: 'searchfield',
                        flex: 1,
                        id: 'eventsearchfield',
                        placeHolder : 'Search',
                        itemId: 'mysearchfield',
                        margin: '5 0 0 0',
                        inputCls: 'innercolor inner-color-update',
                        listeners : {
                            clearicontap: function( ths, input, e, eOpts ){
                                var eventView = Ext.getCmp('EventSearch');
                                eventView.onEventSearchCloseTap()
                            }
                        }
                    },
                    {
                        xtype: 'button',
                        cls: 'searchtop',
                        hidden: true,
                        style : 'position: absolute !important;top: -7px;background-size:contain;',
                        html: '<div class="closebtn"><img src="resources/images/search_close.png"></div>',
                        itemId: 'EventSearchClose',
                        ui: 'plain'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMydataview7ItemTap',
                event: 'itemtap',
                delegate: '#mydataview7'
            },
            {
                fn: 'onShowCategoryListTap',
                event: 'tap',
                delegate: '#ShowCategoryList'
            },
            // {
            //     fn: 'onMysearchfieldClearicontap',
            //     event: 'clearicontap',
            //     delegate: '#eventsearchfield'
            // },
            {
                fn: 'onMysearchfieldKeyup',
                event: 'keyup',
                delegate: '#eventsearchfield'
            },
            {
                fn: 'onEventSearchCloseTap',
                event: 'tap',
                delegate: '#EventSearchClose'
            }
        ]
    },

    onMydataview7ItemTap: function(dataview, index, target, record, e, eOpts) {

            Ext.getCmp('eventsearchfield').setValue('');
            Ext.getStore('NoticesStore').clearFilter();
            Ext.getCmp('EventSearch').hide();
            Ext.getCmp('DNBView').show();
            ShowHideHomePages('EventDetailContainer');
            fnShowEventDetailPageFromHome(record.data);

    },

    onShowCategoryListTap: function(button, e, eOpts) {
        if(Ext.getCmp('CategoryOnSearch'))
            Ext.getCmp('CategoryOnSearch').show();
        else
            Ext.Viewport.add({xtype:'categoryonsearch'}).show();
        Ext.getStore('EventCategorySearchStore').setData(categorySearchListData);
    },

    onMysearchfieldClearicontap: function(textfield, e, eOpts) {
        textfield.setValue('');
        var store=Ext.getStore('NoticesSearchStore');
        store.clearFilter();
        if(categorySelectedOnSearchPage.length>0){
            store.filterBy(function(record, id){
                var tempCatIds=record.get('categoryIds');
                for(j=0;j<categorySelectedOnSearchPage.length;j++){
                    if(tempCatIds.indexOf(':'+categorySelectedOnSearchPage[j]+':')>=0){
                        return true;
                    }
                }

            });
        }

    },

    onMysearchfieldKeyup: function(textfield, e, eOpts) {
        var value = textfield.getValue(),
            store = Ext.getStore('NoticesSearchStore');
        store.clearFilter();
        console.log(value);
        if (value) {

            console.log('here-1');
            console.log(categorySelectedOnSearchPage);
            if(categorySelectedOnSearchPage.length>0){
                store.filterBy(function(record, id){
                    var title = record.get('title');
                    var venu_detail = record.get('venu_detail');

                    var pattern = new RegExp(value, 'gi');

                    if((pattern.test(title) || pattern.test(venu_detail))){
                        var tempCatIds=record.get('categoryIds');
                        for(j=0;j<categorySelectedOnSearchPage.length;j++){
                            if(tempCatIds.indexOf(':'+categorySelectedOnSearchPage[j]+':')>=0){
                                return true;
                            }
                        }
                    }
                });
            }else{
                console.log('here-2');
                store.filterBy(function(record, id){
                    var title = record.get('title');
                    var venu_detail = record.get('venu_detail');

                    var pattern = new RegExp(value, 'gi');

                    if((pattern.test(title) || pattern.test(venu_detail))){
                        return true;
                    }
                });
            }
        }else{
            console.log('here-3');
            console.log(categorySelectedOnSearchPage);

            if(categorySelectedOnSearchPage.length>0){
                store.filterBy(function(record, id){
                    var tempCatIds=record.get('categoryIds');
                    for(j=0;j<categorySelectedOnSearchPage.length;j++){
                        if(tempCatIds.indexOf(':'+categorySelectedOnSearchPage[j]+':')>=0){
                            return true;
                        }
                    }

                });
            }
        }

    },

    onEventSearchCloseTap: function(button, e, eOpts) {
        console.log('here123');
        Ext.getCmp('EventSearch').hide();
        Ext.getCmp('DNBView').show();

    }

});