/*
 * File: app/view/EventVideoPlayer.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */
Ext.define('DNB.view.EventVideoPlayer', {
    extend: 'Ext.Container',
    alias: 'widget.eventvideoplayer',
    requires: ['Ext.Panel', 'Ext.Toolbar', 'Ext.Button', 'Ext.Spacer','Ext.Video'],
    config: {
        itemId: 'EventVideoPlayer',
        items: [{
            xtype: 'toolbar',
            docked: 'top',
            title: 'Video Player',
            items: [{
                xtype: 'button',
                html: 'Back',
                itemId: 'Back',
                ui: 'plain',
                iconCls: 'previousArrowIcon'
            }, {
                xtype: 'spacer'
            }]
        }, {
            xtype: 'panel',
            docked: 'top',
            cls: 'video-player-wrapper-panel-cls',
            layout: {
                type: 'vbox',
                align: 'center',
                pack: 'center'
            },
            listeners: {
                initialize: function(ths) {
                    ths.setHeight(window.innerHeight - 107);
                }
            },
            items: [
                // {
                //     xtype: 'video',
                //     name : 'videoPlayerTag',
                //     width: '100%',
                //     // url: "http://docs.sencha.com/touch/2-1/touch-build/examples/video/resources/media/BigBuck.m4v",
                //     posterUrl: 'resources/images/noticedetail/ViewVideo.PNG',
                //     listeners: {
                //         initialize: function(ths) {
                //             ths.setHeight(window.innerWidth)
                //         }
                //     }
                // }
                // ,
                {
                    xtype: 'panel',
                    // hidden: true,
                    name: 'eventVideoPlayerIframePanel',
                    itemId: 'eventVideoPlayerIFrame',
                    // html: '<iframe height="100%" width="100%" id="iframe-web-id" class="youtube-player" type="text/html" src="http://www.youtube.com/embed/MiG5jPmyDFI?modestbranding=1&showsearch=0&rel=0&theme=dark&showinfo=0&iv_load_policy=3" frameborder="0" allowfullscreen></iframe>',
                    html: '<iframe height="100%" width="100%" id="iframe-web-id" class="youtube-player" type="text/html" src="https://www.youtube.com/embed/HQFvjYHsZ_w?modestbranding=1&showsearch=0&rel=0&theme=dark&showinfo=0&iv_load_policy=3" frameborder="0" allowfullscreen></iframe>',
                    // id: 'EventVideoYoutubePlayer',
                    style: 'background-color: #759E60;margin: 40% 0;width:100%;'
                }
            ]
        }],
        listeners: [{
            fn: 'onBackTap',
            event: 'tap',
            delegate: '#Back'
        }]
    },
    setVideoUrl: function(url) {
        if (url.indexOf('youtube') != -1) {
            var video_id = url.split('v=')[1];
            var ampersandPosition = video_id.indexOf('&');
            if (ampersandPosition != -1) {
                video_id = video_id.substring(0, ampersandPosition);
            }
            this.query('[name=eventVideoPlayerIframePanel]')[0].setHtml('<iframe height="100%" width="100%" id="iframe-web-id" class="youtube-player" type="text/html" src="https://www.youtube.com/embed/' + video_id + '?modestbranding=1&showsearch=0&rel=0&theme=dark&showinfo=0&iv_load_policy=3" frameborder="0" allowfullscreen></iframe>');
        }
    },
    onBackTap: function(button, e, eOpts) {
            // ShowHideHomePages('EventVideosContainer');
            ShowHideHomePages('EventDetailContainer');
        } //,
        // onShowIframeSetUrl: function(url){
        //     console.log('please set ul')
        //     ul = ''
        //     var iframe = document.getElementById('iframe-web-id');
        //     iframe.setAttribute('src', ul)
        // }
});