/*
 * File: app/view/EventList.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DNB.view.EventList', {
    extend: 'Ext.Container',
    alias: 'widget.eventlist',

    requires: [
        'Ext.dataview.DataView',
        'Ext.XTemplate',
        'Ext.Toolbar',
        'Ext.Img',
        'DNB.view.EventComment'
    ],

    config: {
        id: 'EventList',
        layout: 'fit',
        items: [
            {
                xtype: 'dataview',
                onItemDisclosure: 'true',
                itemId: 'mydataview7',
                padding: '5 0 0 0',
                style: 'background-color:white;',
                scrollable: 'vertical',
                disableSelection: false,
                itemTpl: Ext.create('Ext.XTemplate', 
                    '<table style="color:#32AFE7;font-size:14px;margin-left:5px;width: 100%;margin-top:5px;" class="default-botom-border"><tr>',
                    '    <td style="width: 100px;" class="round-img1"><img    style="border-radius: 2px;" width=\"90px\" height=\"90px\" src=\"{[this.GetImageUrl(values.flyer)]}\" onerror=DNB.app.getController(\"Events\").GetNoImageUrl(this)></td>',
                    '    <td class="listtitle">',
                    '        <h2>{title}</h2>',
                    '        <div style="padding:8px 0;">',

                    '            <div style="float:left;margin-left:5px;">',
                    '                <img   width="18px"height="17px" src="resources/images/calendarInEventList.PNG" style="margin-left:1px;">',
                    '            </div>',
                    '            <div style="float:left;color:black;padding-left:5px;margin-top: -3px !important;font-weight:400;margin-left:10px;font-family:Open Sans;font-size: 15px;">{[this.GetFormattedDate(values.end_date)]}</div>',
                    
                    '             <div style="position:absolute;right:10px;"><img style="width:20px;height:20px;" src="resources/images/next-icon.png"></div>',
                    '        </div>',
                    '        <br/>',
                    '        <table style="width:90%;"><tr>',
                    '            <td style="width:30%;" class="comment-icon-cls">',
                    '            <span><img class="comment-icon-cls" src="resources/images/golive/comment.png" style="height:20px;width:20px; margin: 2px 0px 3px 5px;"></span>',
                    '            <span class=" comment-icon-cls totalNumbercomment">{total_comments}</span>',
                    '            </td>',
                    '            ',
                    '            <td style="width:2px;"> <span class="sp">|</span> </td>',
                    '            ',
                    '            <td style="width:30%;" class="is-like-icon-cls">',
                    '            <span> <img class="is-like-icon-cls" style="height:20px;width:20px;" src="{[this.isNoticeLike(values.isLike)]}"> </span>',
                    '            <span class=" is-like-icon-cls totalNumber"> {total_likes} </span>',
                    '            </td>',
                    '            ',
                    '             <td style="width:2px;"> <span class="sp">|</span> </td>',
                    '           ',
                    '            <td class="totalview-icon-cls" style="width:30%;">',
                    '            <span><img class="totalview-icon-cls"  src="resources/images/golive/views.png" style="height:15px;width:25px; margin-top: 5px;"></span>',
                    '            <span  class="totalview-icon-cls totalNumbereye">{total_views}</span>',

                    '            <div class="x-list-disclosure"></div>',
                    '            </td>',
                    '            ',
                    '            </tr>',
                    '        </table>',
                    '    </td>',
                    '    </tr><!--<tr><td colspan="2"><hr size=1></td></tr>--></table>  ',
                    '',
                    '',
                    '       ',
                    ' ',
                    '',
                    {
                        GetImageUrl: function(imageUrl) {
                            return imageBaseUrl+imageUrl;
                        },
                        isNoticeLike: function(isLike) {
                            if(isLike=='yes'){
                                return 'resources/images/golive/likefilled.png';
                            }else{
                                return 'resources/images/golive/like.png';
                            }
                        },
                        GetFormattedDate: function(date) {
                            // console.log(date);//17_5_2015//y/m/d
                            if(date==null || date=='null'){return;}
                            var str=date.split('-');
                            //var d=new Date(str[1]+'-'+str[0]+'-'+str[2]);
                            var d=new Date(str[0]+'-'+str[1]+'-'+str[2]);
                            var m=monthNames[d.getMonth()];
                            var y=d.getFullYear();
                            var day=d.getDate();
                            return m+' '+str[2]+', '+y;
                            // return m+' '+day+', '+y;
                        }
                    }
                ),
                store: 'NoticesStore'
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Go Live',
                 items: [
                    {
                        xtype: 'button',
                        itemId: 'categorylistmenu',
                        name: 'categorylistmenuButton',
                        ui: 'plain',
                        iconCls: 'list',
                        padding: 0,
                        margin: 0
                    },
                    {
                        xtype: 'spacer'
                    }
                    
                ]
            },
            {
                xtype: 'toolbar',
                cls: 'PromotionToolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'image',
                        cls: 'promotionImageFullWidth',
                        src: 'resources/images/promotion.png',
                        height: 50,
                        id: 'promotionImageOnGoLive',
                        
                        width: '100%'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMydataview7ItemTap',
                event: 'itemtap',
                delegate: '#mydataview7'
            },
            {
                fn: 'onPromotionImageOnGoLiveTap',
                event: 'tap',
                delegate: '#promotionImageOnGoLive'
            }
        ]
    },

    onMydataview7ItemTap: function(dataview, index, target, record, e, eOpts) {

        
        console.log(e);
        // return;
        var className=e.target.className;
        if(className.indexOf('is-like-icon-cls')>-1){
               if(record.data.isLike=='yes'){
                 Ext.Msg.alert('','You have already liked this notice.');
                 return;
               }

                if(isLogin==false){
                    loginPageOpenFrom='GoLiveTab';
                    if(Ext.getCmp('Login'))
                        Ext.getCmp('Login').show();
                    else
                        Ext.Viewport.add({xtype:'login'}).show();
                    Ext.getCmp('DNBView').hide();
                }
                else{
                    //Set Like on server
                    Ext.Ajax.request({
                        url:DNB.util.Common.api.addLike,
                        method:'POST',
                        params:{
                            notice_id:record.data.id,
                            user_id:localStorage.getItem('userid')
                        },
                        success: function(res){
                            //alert(res.responseText);
                            var res=Ext.decode(res.responseText);
                            if(res.result.status){
                                Ext.Ajax.request({
                                    url:DNB.util.Common.api.getNoticeById(record.data.id),
                                    success: function(res){
                                        var res=Ext.decode(res.responseText);
                                        
                                        e.target.parentNode.parentNode.innerHTML='<span> <img  class= "is-like-cls" src="resources/images/goliveimages/liked.png"> </span>'+
                                        '<span class="totalNumber">'+res.response_data.Like.length+'</span>';
                                    },failure:function(res){
                                        Ext.Msg.alert('','Internet is not available.');
                                    }
                                });
                            }

                        },failure:function(res){
                            Ext.Msg.alert('','Internet is not available.');
                        }
                    });
                }
            }else if(className.indexOf('comment-icon-cls')>-1){

                if(record.data.comment!='yes'){
                    Ext.Msg.alert('Comments are turned off for this notice.');
                }else{
                    Ext.getCmp('DNBView').hide();
                    if(Ext.getCmp('EventComment'))
                        Ext.getCmp('EventComment').show();
                    else
                        Ext.Viewport.add({xtype:'eventcomment'}).show();
                    commentEventId=record.data.id;
                    commentPageOpenFrom='';
                    if(record.data.comment!='yes'){
                        Ext.getCmp('SendComment').disable();
                    }else{
                        Ext.getCmp('SendComment').enable();
                    }
                    DNB.app.getController('Events').GetEventCommentList(record.data.id);
                }

            }else if(className.indexOf('totalview-icon-cls')>-1){

            }else{
                eventDetailPageOpenFrom = 'GoLive';
                fnShowEventDetailPageFromHome(record.data);
            }





        // if(e.target.nodeName=='IMG'){
        //     // if(e.target.parentNode.innerHTML.indexOf('like.png')>=0){
        //     if(e.target.className.contains('is-like-icon-cls')){
        //        if(record.data.isLike=='yes'){
        //          Ext.Msg.alert('','You have already liked this notice.');
        //          return;
        //        }

        //         if(isLogin==false){
        //             loginPageOpenFrom='GoLiveTab';
        //             if(Ext.getCmp('Login'))
        //                 Ext.getCmp('Login').show();
        //             else
        //                 Ext.Viewport.add({xtype:'login'}).show();
        //             Ext.getCmp('DNBView').hide();
        //         }
        //         else{
        //             //Set Like on server
        //             Ext.Ajax.request({
        //                 url:DNB.util.Common.api.addLike,
        //                 method:'POST',
        //                 params:{
        //                     notice_id:record.data.id,
        //                     user_id:localStorage.getItem('userid')
        //                 },
        //                 success: function(res){
        //                     //alert(res.responseText);
        //                     var res=Ext.decode(res.responseText);
        //                     if(res.result.status){
        //                         Ext.Ajax.request({
        //                             url:DNB.util.Common.api.getNoticeById(record.data.id),
        //                             success: function(res){
        //                                 var res=Ext.decode(res.responseText);
                                        
        //                                 e.target.parentNode.parentNode.innerHTML='<span> <img  class= "is-like-cls" src="resources/images/goliveimages/liked.png"> </span>'+
        //                                 '<span class="totalNumber">'+res.response_data.Like.length+'</span>';
        //                             },failure:function(res){
        //                                 Ext.Msg.alert('','Internet is not available.');
        //                             }
        //                         });
        //                     }

        //                 },failure:function(res){
        //                     Ext.Msg.alert('','Internet is not available.');
        //                 }
        //             });
        //         }
        //     }
        //     else if(e.target.parentNode.innerHTML.indexOf(imageBaseUrl)>=0){
        //         eventDetailPageOpenFrom = 'GoLive';
        //         fnShowEventDetailPageFromHome(record.data);
        //     }
        //     else{
        //         if(record.data.comment!='yes'){
        //             Ext.Msg.alert('Comments are turned off for this notice.');
        //         }else{
        //             Ext.getCmp('DNBView').hide();
        //             if(Ext.getCmp('EventComment'))
        //                 Ext.getCmp('EventComment').show();
        //             else
        //                 Ext.Viewport.add({xtype:'eventcomment'}).show();
        //             commentEventId=record.data.id;
        //             commentPageOpenFrom='';
        //             if(record.data.comment!='yes'){
        //                 Ext.getCmp('SendComment').disable();
        //             }else{
        //                 Ext.getCmp('SendComment').enable();
        //             }
        //             DNB.app.getController('Events').GetEventCommentList(record.data.id);
        //         }

        //     }
        // }else{
        //     if(record.data.comment!='yes'){
        //         Ext.Msg.alert('Comments are turned off for this notice.');
        //     }else{
        //         Ext.getCmp('DNBView').hide();
        //         if(Ext.getCmp('EventComment'))
        //             Ext.getCmp('EventComment').show();
        //         else
        //             Ext.Viewport.add({xtype:'eventcomment'}).show();
        //         commentEventId=record.data.id;
        //         commentPageOpenFrom='';
        //         if(record.data.comment!='yes'){
        //             Ext.getCmp('SendComment').disable();
        //         }else{
        //             Ext.getCmp('SendComment').enable();
        //         }
        //         DNB.app.getController('Events').GetEventCommentList(record.data.id);
        //     }
        // }

    },

    onPromotionImageOnGoLiveTap: function(image, e, eOpts) {
        isBannerActive=false;
        audioPlayerOpenFrom='GoLive';
        
        DNB.app.getController('Events').ShowPromotionPopup('promotionImageOnGoLive');
    }

});