/*
 * File: app/view/ExtJsLoader.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DNB.view.ExtJsLoader', {
    extend: 'Ext.Container',
    alias: 'widget.extjsloader',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        centered: true,
        height: 80,
        id: 'ExtJsLoader',
        style: 'background-color:white;',
        width: 200,
        modal: true,
        tpl: [
            '<table style="width:200px;">',
            '    <tr>',
            '        <td style="width:20px;background-color:{One};">&nbsp;</td>',
            '        <td style="width:20px;background-color:{Two};">&nbsp;</td>',
            '        <td style="width:20px;background-color:{Three};">&nbsp;</td>',
            '        <td style="width:20px;background-color:{Four};">&nbsp;</td>',
            '        <td style="width:20px;background-color:{Five};">&nbsp;</td>',
            '        <td style="width:20px;background-color:{Six}};">&nbsp;</td>',
            '        <td style="width:20px;background-color:{Seven};">&nbsp;</td>',
            '        <td style="width:20px;background-color:{Eight};">&nbsp;</td>',
            '        <td style="width:20px;background-color:{Nine};">&nbsp;</td>',
            '        <td style="width:20px;background-color:{Ten};">&nbsp;</td>',
            '    </tr>',
            '    <tr>',
            '        <td colspan="10" style="text-align:center;">Loading Audio</td>',
            '    </tr>',
            '</table>'
        ]
    }

});