/*
 * File: app/view/ForgotPassword.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DNB.view.ForgotPassword', {
    extend: 'Ext.Container',
    alias: 'widget.forgotpassword',

    requires: [
        'Ext.Toolbar',
        'Ext.Spacer',
        'Ext.Button',
        'Ext.Panel',
        'Ext.field.Email'
    ],

    config: {
        centered: true,
        height: 250,
        id: 'ForgotPassword',
        style: 'background-color:white;  border-radius: 4px;',
        ui: 'light',
        width: 310,
        hideOnMaskTap: false,
        modal: true,
        items: [
            {
                xtype: 'toolbar',
                cls: 'popheader',
                docked: 'top',
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        html: '<div><img  width="16" src="resources/images/CloseBlueIcon.JPG"></div>',
                        itemId: 'CloseButton',
                        cls: 'forgotPasswordViewCloseButtonCls',
                        ui: 'plain'
                    }
                ]
            },
            {
                xtype: 'panel',
                html: ' Enter your Email Address',
                margin: 0,
                style: 'color:rgb(220, 178, 9);text-align:center;font-weight:bold;'
            },
            {
                xtype: 'emailfield',
                id: 'ResetEmail',
                margin: '20 0 0 10% 0',
                padding: 5,
                style: 'border:1px solid rgb(220, 178, 9);border-radius:3px;color:rgb(220, 178, 9);',
                width: '80%',
                clearIcon: false,
                placeHolder: 'johndoe@gmail.com'
            },
            {
                xtype: 'button',
                cls: 'popbtn',
                docked: 'bottom',
                itemId: 'SendButton',
                text: 'Send'
            }
        ],
        listeners: [
            {
                fn: 'onCloseButtonTap',
                event: 'tap',
                delegate: '#CloseButton'
            },
            {
                fn: 'onSendButtonTap',
                event: 'tap',
                delegate: '#SendButton'
            }
        ]
    },

    onCloseButtonTap: function(button, e, eOpts) {
                Ext.getCmp('ForgotPassword').hide();
                //Ext.getCmp('Login').show();
    },

    onSendButtonTap: function(button, e, eOpts) {
        var email=Ext.getCmp('ResetEmail').getValue();
        var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
        var checkemail=filter.test(email);

        if(email==''){
            Ext.Msg.alert('','Email is mandatory!');
        }
        else if(!checkemail){
            Ext.Msg.alert('','Invalid Email!');
        }
        else{
            Ext.Viewport.setMasked({xtype:'loadmask',message:'Loading notices'});
            Ext.Ajax.request({
                url:DNB.util.Common.api.resetPassword,
                method:'POST',
                params :  {
                    email:email
                },
                success:function(res,options){
                    Ext.Viewport.setMasked(false);
                    console.log('success:'+res.responseText);
                    var res=Ext.decode(res.responseText).response_data;

                    if(res.status){
                        Ext.getCmp('ForgotPassword').hide();
                        if(res.message.indexOf('Mail has been send')>=0){
                            Ext.Msg.alert('','Please check your email and reset the password.');
                        }
                        else
                            Ext.Msg.alert(res.message);
                    }else{
                        if(res.isActive=='block'){
                            Ext.Msg.alert('','Please verify and activate your account first.');

                            var btn=confirm('Would you like to resend verification link?');
                            if(btn==true){
                                Ext.getCmp('ForgotPassword').hide();
                                if(Ext.getCmp('ReSendLink')){
                                    Ext.getCmp('ReSendLink').show();
                                }
                                else
                                    Ext.Viewport.add({xtype:'resendlink'}).show();
                                Ext.getCmp('ReSendEmail').setValue('');
                            }
                            else{
                                Ext.getCmp('ForgotPassword').hide();
                            }
                        }
                        else if(res.message.indexOf('Invalid Email')>=0){
                            Ext.Msg.alert('','Email does not exist!');//Please provide active mail id!');
                        }
                    }

                },
                failure:function(res,options){
                    Ext.Viewport.setMasked(false);
                    Ext.Msg.alert('','failure'+res.responseText);
                }

            });

        }

    }

});