/*
 * File: app/view/Gallery.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DNB.view.Gallery', {
    extend: 'Ext.Container',
    alias: 'widget.gallery',

    requires: [
        'Ext.Panel',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.Img'
    ],

    config: {
        layout: 'fit',
        items: [
            {
                xtype: 'panel',
                id: 'GalleryPanel',
                layout: 'vbox',
                scrollable: 'vertical'
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Gallery',
                items: [
                    {
                        xtype: 'button',
                        html: 'Back',
                        itemId: 'Back',
                        ui: 'plain',
                        iconCls: 'previousArrowIcon'
                    },
                    {
                        xtype: 'spacer'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                cls: 'PromotionToolbar',
                docked: 'bottom',
                hidden: true,
                items: [
                    {
                        xtype: 'image',
                        cls: 'promotionImageFullWidth',
                        height: 100,
                        id: 'promotionImageOnGallery',
                        itemId: 'myimg14',
                        width: '100%'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onBackTap',
                event: 'tap',
                delegate: '#Back'
            },
            {
                fn: 'onPromotionImageOnGalleryTap',
                event: 'tap',
                delegate: '#promotionImageOnGallery'
            }
        ]
    },

    onBackTap: function(button, e, eOpts) {

        Ext.getCmp('GalleryContainer').hide();
        Ext.getCmp('GalleryImageContainer').hide();
        if(galleryPageOpenFrom==''){
            Ext.getCmp('AlbumContainer').show();
        }else{
            Ext.getCmp('MainTabView').setActiveItem(0);
            ShowHideHomePages('EventDetailContainer');
        }
    },

    onPromotionImageOnGalleryTap: function(image, e, eOpts) {
        isBannerActive=false;
        audioPlayerOpenFrom='Gallery';
        DNB.app.getController('Events').ShowPromotionPopup('PromotionImageOnGallery');
    }

});