/*
 * File: app/view/Login.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DNB.view.Login', {
    extend: 'Ext.Container',
    alias: 'widget.login',

    requires: [
        'Ext.Toolbar',
        'Ext.Panel',
        'Ext.Spacer',
        'Ext.Img',
        'Ext.Label',
        'Ext.field.Email',
        'Ext.field.Password',
        'Ext.Button',
        'DNB.view.ForgotPassword',
        'DNB.view.Register',
        'DNB.view.ReSendLink',
        'DNB.view.UserEmail'
    ],

    config: {
        id: 'Login',
        scrollable: 'vertical',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 60,
                title: 'Login'
            },
            {
                xtype: 'panel',
                cls: 'mainheader',
                height: '19%',
                hidden: true,
                layout: 'vbox',
                items: [
                    {
                        xtype: 'spacer',
                        flex: 1
                    },
                    {
                        xtype: 'panel',
                        html: '<i> Digital<br/>Noticeboard </i>',
                        itemId: 'digitalnoticeboardPanel',
                        style: 'text-align:center;background-color:2b2b2b;color:white;font-family: lab_sans_proregular;'
                    },
                    {
                        xtype: 'spacer',
                        flex: 1
                    }
                ]
            },
            {
                xtype: 'panel',
                cls: 'mainheader',
                height: 120,
                html: '<i> Digital<br/>Noticeboard </i>',
                itemId: 'digitalnoticeboardPanel2',
                style: '',
                items: [{
                        xtype: 'spacer',
                        height: 15
                    }]
            },{
                xtype: 'panel',
                cls : 'loginViewTwitterPanelCls',
                layout:{
                    type : 'vbox',
                    pack : 'center',
                    align : 'center'
                },
                items : [{
                    xtype : 'button',
                    width : '70%',
                    ui : 'plain',
                    itemId: 'LoginWithTwitter',
                    iconCls : 'twitter-icon-cls',
                    text: 'Login With Twitter'
                    
                }]
            },
            {
                xtype: 'panel',
                cls : 'loginViewFaceBookPanelCls',
                layout:{
                    type : 'vbox',
                    pack : 'center',
                    align : 'center'
                },
                items : [{
                    xtype : 'button',
                    width : '70%',
                    ui : 'plain',
                    itemId: 'LoginWithFacebook',
                    iconCls : 'facebook-icon-cls',
                    text: 'Login With Facebook'

                }]
            },
            {
                xtype: 'panel',
                height: '5%',
                hidden: true,
                style: 'background-color:#2B2B2B;color:white;',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'spacer',
                        flex: 1,
                        html: '<hr size=1 style="color:#898989;"/>',
                        padding: '0 0 0 10%'
                    },
                    {
                        xtype: 'label',
                        flex: 1,
                        height: '5%',
                        html: 'or',
                        style: 'text-align:center;vertical-align:center;'
                    },
                    {
                        xtype: 'spacer',
                        flex: 1,
                        html: '<hr size=1 style="color:#898989;"/>',
                        padding: '0 10% 0 0'
                    }
                ]
            },
            {
                xtype: 'image',
                height: '5%',
                itemId: 'OR',
                style: 'background-color:#2B2B2B;',
                src: 'resources/images/or.PNG'
            },
            {
                xtype: 'emailfield',
                id: 'txtUserEmail',
                itemId: 'txtUserEmail',
                style: 'background-color:#3F3F3F;border-bottom:1px solid #2d2d2d;color:white; ',
                clearIcon: false,
                inputCls: 'loginfield',
                placeHolder: 'Username'
            },
            {
                xtype: 'panel',
                style: 'background-color:#3f3f3f;',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'passwordfield',
                        flex: 1,
                        id: 'txtUserPassword',
                        itemId: 'txtUserPassword',
                        style: 'background-color:#3f3f3f;',
                        clearIcon: false,
                        inputCls: 'passwordfield',
                        autoComplete: false,
                        autoCorrect: false,
                        placeHolder: 'Password'
                    },
                    {
                        xtype: 'button',
                        height: 60,
                        width: 60,
                        html: '<img width="32px" height="32px" src="resources/images/question.png">',
                        itemId: 'ForgotPasswordButton',
                        padding: '10 10 5 2',
                        width: 60,
                        style: 'background-color:#3f3f3f',
                        ui: 'plain'
                    }
                ]
            },
            {
                xtype: 'button',
                cls: 'signupbtn',
                height: 60,
                itemId: 'LoginButton',
                text: 'Sign in'
            },
            {
                xtype: 'panel',
                height: '8%',
                hidden: true,
                style: 'background-color:#2B2B2B;color:white;',
                layout: 'fit',
                items: [
                    {
                        xtype: 'label',
                        centered: false,
                        height: '100%',
                        html: 'Dont have an account?',
                        margin: '5 0 0 0',
                        style: 'text-align:center;',
                        width: '100%'
                    }
                ]
            },
            {
                xtype: 'panel',
                height: '25%',
                hidden: true,
                style: 'background-color:#2B2B2B;color:white;',
                layout: 'vbox',
                items: [
                    {
                        xtype: 'button',
                        height: '30%',
                        html: '<b>Sign up</b>',
                        itemId: 'Signup1',
                        style: 'background-color:#2B2B2B;color:white; text-decoration: underline;',
                        ui: 'plain',
                        text: 'Sign up'
                    },
                    {
                        xtype: 'spacer',
                        height: '10%'
                    },
                    {
                        xtype: 'label',
                        height: 80,
                        html: 'By signing in you agree with the term and conditions of Digital Noticeboard',
                        style: 'font-size:14px;text-align:center;'
                    }
                ]
            },
            {
                xtype: 'panel',
                height: 170,
                style: 'background-color:#2b2b2b;color:white;',
                layout: 'fit',
                items: [
                    {
                        xtype: 'label',
                        height: 50,
                        html: 'Don\'t have an account?',
                        padding: '15 0 0 0',
                        style: 'background-color:#2b2b2b;color:white;text-align:center;'
                    },
                    {
                        xtype: 'button',
                        itemId: 'Signup',
                        margin: '0 0 0 5',
                        padding: '',
                        style: 'color:white;    text-decoration: underline;',
                        ui: 'plain',
                        text: '<b>Sign up</b>'
                    },
                    {
                        xtype: 'spacer',
                        height: '10%'
                    },
                    {
                        xtype: 'label',
                        html: 'By signing in you agree with the terms and conditions of Digital Noticeboard',
                        style: 'font-size:14px;text-align:center;background:#2B2B2B;'
                    }
                ]
            }
        ]
        // ,
        // listeners: [
        //     {
        //         fn: 'onTxtUserEmailFocus',
        //         event: 'focus',
        //         delegate: '#txtUserEmail'
        //     },
        //     {
        //         fn: 'onTxtUserEmailBlur',
        //         event: 'blur',
        //         delegate: '#txtUserEmail'
        //     }
        // ]
    },

    onTxtUserEmailFocus: function(textfield, e, eOpts) {
        isUserNameFocus=true;
        var ost = textfield.element.dom.offsetTop;
        this.getScrollable().getScroller().scrollTo(0, ost);
    },

    onTxtUserEmailBlur: function(textfield, e, eOpts) {
        isUserNameFocus=false;
        var ost = textfield.element.dom.offsetTop;
        this.getScrollable().getScroller().scrollTo(0, ost);
    }

});