/*
 * File: app/view/NoticeFreeLocations.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DNB.view.NoticeFreeLocations', {
    extend: 'Ext.Container',
    alias: 'widget.noticefreelocations',

    requires: [
        'Ext.dataview.DataView',
        'Ext.XTemplate'
    ],

    config: {
        centered: true,
        height: '30%',
        id: 'NoticeFreeLocations',
        left: '25%',
        width: '50%',
        hideOnMaskTap: true,
        modal: true,
        items: [
            {
                xtype: 'dataview',
                height: 200,
                itemId: 'NoticeFreeLocationsList',
                style: 'background-color:#36AEE4;color:white;',
                itemTpl: [
                    '<div>{address}</div>'
                ],
                store: 'FreeLocationsStore'
            }
        ],
        listeners: [
            {
                fn: 'onNoticeFreeLocationsListItemTap',
                event: 'itemtap',
                delegate: '#NoticeFreeLocationsList'
            }
        ]
    },

    onNoticeFreeLocationsListItemTap: function(dataview, index, target, record, e, eOpts) {
        document.getElementById('locationField').value=record.data.address2;
        // Ext.getCmp('EventLocationOnEventPage').setValue(record.data.address2);
        Ext.getCmp('EventLocationCityOnEventPage').setValue(record.data.city);
        Ext.getCmp('EventLocationStateOnEventPage').setValue(record.data.state);
        Ext.getCmp('EventLocationZipOnEventPage').setValue(record.data.zip);
        Ext.getCmp('NoticeFreeLocations').hide();
    }

});