/*
 * File: app/view/PromotionAudioPlayer.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DNB.view.PromotionAudioPlayer', {
    extend: 'Ext.Container',
    alias: 'widget.promotionaudioplayer',

    requires: [
        'Ext.Panel',
        'Ext.Audio',
        'Ext.Spacer',
        'Ext.Button',
        'Ext.field.Slider',
        'Ext.Toolbar'
    ],

    config: {
        centered: true,
        height: 250,
        id: 'PromotionAudioPlayer',
        style: 'background-color:white;',
        width: 300,
        hideOnMaskTap: false,
        modal: true,
        items: [
            {
                xtype: 'panel',
                hidden: true,
                id: '',
                itemId: 'Audio',
                items: [
                    {
                        xtype: 'audio',
                        id: 'PromotionAudioPlayertool',
                        url: 'http://192.169.199.42/DNB/DNB_admin/img/audio/Kalimba.mp3'
                    }
                ]
            },
            {
                xtype: 'panel',
                hidden: true,
                id: 'PromotionAudioPlayerPanel'
            },
            {
                xtype: 'panel',
                cls: 'audioplayer',
                height: 200,
                margin: '0 0 0 0',
                style: 'background-image:url(resources/css/img/sample.jpg);',
                layout: 'vbox',
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'panel',
                        height: 88,
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'button',
                                cls: 'playbutton',
                                height: 85,
                                html: '<img src=\'resources/images/play.png\'>',
                                id: 'PromotionMediaPlayButton',
                                itemId: 'mybutton25',
                                ui: 'action',
                                width: 85,
                                iconCls: 'play'
                            },
                            {
                                xtype: 'sliderfield',
                                flex: 1,
                                id: 'PromotionMediaAudioSlider',
                                itemId: 'mysliderfield1',
                                margin: '0 0 0 5'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Audio Player',
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        html: '<div><img src="resources/images/CloseBlueIcon.JPG"></div>',
                        itemId: 'CloseAudioPlayer',
                        margin: '0 -5 0 0',
                        ui: 'plain',
                        iconAlign: 'right'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onPromotionMediaPlayButtonTap',
                event: 'tap',
                delegate: '#PromotionMediaPlayButton'
            },
            {
                fn: 'onPromotionMediaAudioSliderChange',
                event: 'change',
                delegate: '#PromotionMediaAudioSlider'
            },
            {
                fn: 'onPromotionMediaAudioSliderDragEnd',
                event: 'dragend',
                delegate: '#PromotionMediaAudioSlider'
            },
            {
                fn: 'onCloseAudioPlayerTap',
                event: 'tap',
                delegate: '#CloseAudioPlayer'
            }
        ]
    },

    onPromotionMediaPlayButtonTap: function(button, e, eOpts) {
        var PromotionMediaPlayButton=Ext.select('#PromotionMediaPlayButton').elements[0];
        if(media){
            if(isAudioPlaying){
                media.pause();
                isAudioPlaying=false;
                PromotionMediaPlayButton.className ='x-button x-iconalign-center x-button-action x-sized playbutton x-layout-box-item play';

            }
            else{
                media.play();
                isAudioPlaying=true;
                PromotionMediaPlayButton.className ='x-button x-iconalign-center x-button-action x-sized playbutton x-layout-box-item loading';
            }
        }

    },

    onPromotionMediaAudioSliderChange: function(me, sl, thumb, newValue, oldValue, eOpts) {
        var position=newValue;
        if(position=='' || position==null)
            position=0;
        media.seekTo(position);
    },

    onPromotionMediaAudioSliderDragEnd: function(sliderfield, sl, thumb, value, e, eOpts) {
        var position=sliderfield.getValue()[0];
        if(position=='' || position==null)
            position=0;
        media.seekTo(position);
    },

    onCloseAudioPlayerTap: function(button, e, eOpts) {
        media.pause();
        Ext.getCmp('PromotionAudioPlayer').hide();

    }

});