/*
 * File: app/view/Register.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DNB.view.Register', {
    extend: 'Ext.Container',
    alias: 'widget.register',

    requires: [
        'Ext.Spacer',
        'Ext.field.Email',
        'Ext.field.Password',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.Button',
        'Ext.TitleBar',
        'Ext.Label'
    ],

    config: {
        id: 'Register',
        scrollable: 'vertical',
        items: [
            {
                xtype: 'panel',
                cls: 'mainheader',
                height: 100,
                html: '<i> Digital<br/>Noticeboard </i>',
                itemId: 'digitalnoticeboardPanel1',
                style: '',
                items: [
                    {
                        xtype: 'spacer',
                        height: 8
                    }
                ]
            },
            {
                xtype: 'emailfield',
                itemId: 'email',
                style: 'background-color:#3F3F3F;border-bottom:1px solid #2d2d2d;color:white;',
                clearIcon: false,
                inputCls: 'emailfield',
                required: true,
                placeHolder: 'Email Address'
                // ,
                // listeners: {
                //     focus: function(comp, e, eopts) {
                //         var ost = comp.element.dom.offsetTop;
                //         Ext.getCmp('Register').getScrollable().getScroller().scrollTo(0, ost);
                //     }
                // }
            },
            {
                xtype: 'textfield',
                itemId: 'UsernameInRegister',
                style: 'background-color:#3F3F3F;border-bottom:1px solid #2d2d2d;color:white;',
                clearIcon: false,
                inputCls: 'loginfield',
                placeHolder: 'Username'
                // ,
                // listeners: {
                //     focus: function(comp, e, eopts) {
                //         var ost = comp.element.dom.offsetTop;
                //         Ext.getCmp('Register').getScrollable().getScroller().scrollTo(0, ost);
                //     }
                // }
            },
            {
                xtype: 'passwordfield',
                itemId: 'password',
                style: 'background-color:#3F3F3F;border-bottom:1px solid #2d2d2d;color:white;',
                clearIcon: false,
                inputCls: 'passwordfield',
                required: true,
                placeHolder: 'Password'
                // ,
                // listeners: {
                //     focus: function(comp, e, eopts) {
                //         var ost = comp.element.dom.offsetTop;
                //         Ext.getCmp('Register').getScrollable().getScroller().scrollTo(0, ost);
                //     }
                // }
            },
            {
                xtype: 'passwordfield',
                itemId: 'confirmPassword',
                style: 'background-color:#3F3F3F;border-bottom:1px solid #2d2d2d;color:white;',
                clearIcon: false,
                inputCls: 'passwordfield',
                placeHolder: 'Confirm Password'
                // ,
                // listeners: {
                //     focus: function(comp, e, eopts) {
                //         var ost = comp.element.dom.offsetTop;
                //         Ext.getCmp('Register').getScrollable().getScroller().scrollTo(0, ost);
                //     }
                // }
            },
            {
                xtype: 'datepickerfield',
                cls: 'dob',
                itemId: 'dob',
                style: 'background-color:#3F3F3F;border-bottom:1px solid #2d2d2d;color:white;',
                inputCls: 'dobfield',
                labelWidth: '50%',
                placeHolder: 'Date of Birth',
            //     picker: {
            //     yearFrom: 1950
            // },
                picker: {
                    yearFrom: 1950,
                    doneButton: {
                        itemId: 'Done',
                        ui: 'plain'
                    },
                    cancelButton: {
                        itemId: 'Cancel',
                        ui: 'plain'
                    }
                }
            },
            {
                xtype: 'button',
                cls: 'signupbtn',
                height: 60,
                itemId: 'btnSignUp',
                text: 'Sign up'
            },
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Sign up'
            },
            {
                xtype: 'panel',
                height: 170,
                style: 'background-color:#2b2b2b;color:white;',
                layout: 'fit',
                items: [
                    {
                        xtype: 'label',
                        height: 50,
                        html: 'Already have an account?',
                        padding: '05 0 0 0',
                        style: 'background-color:#2b2b2b;color:white;text-align:center;'
                    },
                    {
                        xtype: 'button',
                        itemId: 'SignInButton',
                        margin: '0 0 0 5',
                        padding: '',
                        style: 'color:white;    text-decoration: underline;',
                        ui: 'plain',
                        text: '<b>Sign in</b>'
                    },
                    {
                        xtype: 'spacer',
                        height: '10%'
                    },
                    {
                        xtype: 'label',
                        html: 'By signing up you agree with the terms and conditions of Digital Noticeboard',
                        style: 'font-size:14px;text-align:center;background: #2B2B2B;'
                    }
                ]
            }
        ]
        // ,
        // listeners: [
        //     {
        //         fn: 'onDoneTap',
        //         event: 'tap',
        //         delegate: '#Done'
        //     },
        //     {
        //         fn: 'onCancelTap',
        //         event: 'tap',
        //         delegate: '#Cancel'
        //     },
        //     {
        //         fn: 'onDobFocus',
        //         event: 'focus',
        //         delegate: '#dob'
        //     }
        // ]
    },

    onDoneTap: function(button, e, eOpts) {

    },

    onCancelTap: function(button, e, eOpts) {

    },

    onDobFocus: function(selectfield, e, eOpts) {
        //Ext.getCmp('Register').getComponent('dob').getValue(new Date());
         //this.query('#dob')[0].getDatePicker().yearFrom = 1950;
    }

});