/*
 * File: app/view/ReSendLink.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DNB.view.ReSendLink', {
    extend: 'Ext.Container',
    alias: 'widget.resendlink',

    requires: [
        'Ext.Toolbar',
        'Ext.Spacer',
        'Ext.Button',
        'Ext.Panel',
        'Ext.field.Email',
        'Ext.Label'
    ],

    config: {
        centered: true,
        height: 299,
        id: 'ReSendLink',
        style: 'background-color:White;',
        width: 243,
        hideOnMaskTap: false,
        modal: true,
        items: [
            {
                xtype: 'toolbar',
                cls: 'popheader',
                docked: 'top',
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        html: '<div><img  width="16" src="resources/images/CloseBlueIcon.JPG"></div>',
                        itemId: 'CloseButton1',
                        margin: '0 -5 0 0',
                        ui: 'plain'
                    }
                ]
            },
            {
                xtype: 'panel',
                html: 'Resend',
                margin: 0,
                style: 'color:rgb(220, 178, 9);text-align:center;font-weight:bold;'
            },
            {
                xtype: 'emailfield',
                hidden: true,
                id: 'ReSendEmail123',
                style: 'border-bottom:1px solid gray;',
                clearIcon: false,
                placeHolder: 'Email'
            },
            {
                xtype: 'emailfield',
                id: 'ReSendEmail',
                margin: '20 0 0 10% 0',
                padding: 5,
                style: 'border:1px solid rgb(220, 178, 9);border-radius:3px;color:rgb(220, 178, 9);',
                width: '80%',
                clearIcon: false,
                placeHolder: 'johndoe@gmail.com'
            },
            {
                xtype: 'label',
                centered: false,
                hidden: true,
                html: 'Please Verify Your E-mail',
                id: 'ForgotPassword1',
                style: 'text-align:center;',
                styleHtmlContent: true
            },
            {
                xtype: 'panel',
                html: 'Please Verify Your E-mail',
                margin: '30 0 0 0',
                style: 'color:rgb(220, 178, 9);text-align:center;font-weight:bold;'
            },
            {
                xtype: 'button',
                cls: 'popbtn',
                height: 50,
                itemId: 'ResendLinkButton',
                margin: '50 0 0 0',
                style: 'color:white;background-color: rgb(220, 178, 9);',
                ui: 'plain',
                text: 'Resend Link'
            }
        ],
        listeners: [
            {
                fn: 'onCloseButtonTap1',
                event: 'tap',
                delegate: '#CloseButton1'
            },
            {
                fn: 'onResendLinkButtonTap',
                event: 'tap',
                delegate: '#ResendLinkButton'
            }
        ]
    },

    onCloseButtonTap1: function(button, e, eOpts) {
        var ReSendLink=this;
        ReSendLink.getComponent('ReSendEmail').setValue('');
        Ext.getCmp('ReSendLink').hide();
        //Ext.getCmp('Login').show();
    },

    onResendLinkButtonTap: function(button, e, eOpts) {
        var ReSendLink=this;
        var email=ReSendLink.getComponent('ReSendEmail').getValue();
        var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
        var checkemail=filter.test(email);

        if(email==''){
            Ext.Msg.alert('','Email is mandatory!');
        }
        else if(!checkemail){
            Ext.Msg.alert('','Invalid Email!');
        }
        else  if(localStorage.getItem('email')!=''
                 && localStorage.getItem('email')!=null
                 && localStorage.getItem('email')!=undefined
                 &&  localStorage.getItem('email')!=email){
            Ext.Msg.alert('','Email does not match with registered email');//+localStorage.getItem('email'));
        }
        else{
            Ext.Ajax.request({
                url:DNB.util.Common.api.resendEmail,
                method:'POST',
                params :  {
                    email:email
                },
                success:function(res,options){
                    //alert('success:'+res.responseText);
                    var res=Ext.decode(res.responseText).Result;
                    ReSendLink.getComponent('ReSendEmail').setValue('');
                    Ext.getCmp('ReSendLink').hide();
                    //alert(res.Status);
                    if(res.status){

                        Ext.getCmp('Login').hide();
                        //alert(res.Message);
                        Ext.Msg.alert('','Verification mail has been sent to your email id. Please check your email and activate your account.');

                        Ext.getCmp('DNBView').show();

                    }

                },
                failure:function(res,options){
                    Ext.Msg.alert('','failure'+res.responseText);
                    Ext.getCmp('ReSendLink').hide();
                }

            });

        }

    }

});