/*
 * File: app/view/Splash.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DNB.view.Splash', {
    extend: 'Ext.Container',
    alias: 'widget.splash',

    requires: [
        'Ext.Img'
    ],

    config: {
        fullscreen: true,
        id: 'Splash',
        items: [
            {
                xtype: 'image',
                centered: true,
                height: '100%',
                style: 'background-size: 100% 100% !important;',
                width: '100%',
                src: 'resources/images/splash.PNG'
            }
        ]
    }

});