/*
 * File: app/view/UserProfile.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */
Ext.define('DNB.view.UserProfile', {
    extend: 'Ext.Container',
    alias: 'widget.userprofile',
    requires: ['Ext.Panel', 'Ext.Spacer', 'Ext.Img', 'Ext.Label', 'Ext.XTemplate'],
    config: {
        centered: true,
        id: 'UserProfile',
        cls: 'userprofile-popup-wrapper',
        hideOnMaskTap: false,
        layout: {
            type: 'vbox',
            align: 'center',
            pack: 'start'
        },
        modal: true,
        items: [{
                xtype: 'panel',
                cls : 'userprofilepopup-image-wrapper-cls',
                items: [{
                    xtype: 'image',
                    id: 'userImage',
                    src: 'resources/images/default-user.png',
                    cls: 'userprofilepopup-image-cls'
                }]
            }, {
                xtype: 'label',
                id: 'userNameLabel',
                cls : 'user-profile-name-cls',
                html: 'UserName'
            }, {
                xtype: 'image',
                src: 'resources/images/more-h.png',
                height: 40,
                width: 40,
                // margin:15,
                style:'background-size:contain;'
            }, {
                xtype: 'label',
                id: 'statusLabel',
                cls : 'user-status-label-cls',
                html: 'i speak my mind i never mind what i speak'
            }, {
                xtype: 'label',
                id: 'totalCommentsLabel',
                cls : 'user-profile-ref-number-cls',
                html: '2232'
            },{
                xtype : 'button',
                ui : 'plain',
                id : 'close',
                cls : 'bottom-cross-blue-transparent-btn-cls cross-blue-btn-icon-cls'
            }],
            listeners: [
                {
                    fn: 'onCloseTap',
                    event: 'tap',
                    delegate: '#close'
                }
            ]

            // =======================================
            // old popup designed by tpl
            // =======================================
            // tpl: Ext.create('Ext.XTemplate', 
            //     '<table style="width:100%"><tr><td style="width:20%;padding:10px;">',
            //     '    <img width="50px" height="40px" src="{[this.GetImageUrl(values.userimage)]}" ',
            //     '         onerror=DNB.app.getController(\'Events\').GetNoImageUrl(this)>',
            //     '    </td>',
            //     '    <td style="padding:10px;width:80%;border-bottom:0px solid gray;">',
            //     '        <table style="width:100%">',
            //     '            <tr><td colspan="2" style="color:#32AFE7;">',
            //     '                {username}',
            //     '                <span style="width:50px;background-color:#32AFE7;color:white;margin-left:10px;border-radius:15px;">&nbsp;{totalvalues}&nbsp;</span>',
            //     '            </td></tr>',
            //     '        </table>',
            //     '    </td>',
            //     '    </tr></table>',
            //     {
            //         GetImageUrl: function(imageUrl) {
            //             return imageBaseUrl+imageUrl;
            //         }
            //     }
            // ),
            // items: [
            //     {
            //         xtype: 'panel',
            //         height: 100,
            //         hidden: true,
            //         padding: 5,
            //         style: 'border-bottom:1px solid gray;',
            //         width: '100%',
            //         layout: 'hbox',
            //         items: [
            //             {
            //                 xtype: 'spacer',
            //                 flex: 1
            //             },
            //             {
            //                 xtype: 'panel',
            //                 height: 50,
            //                 width: 50,
            //                 layout: 'fit',
            //                 items: [
            //                     {
            //                         xtype: 'image',
            //                         height: 60,
            //                         id: 'UserProfileImageMyZone',
            //                         width: 50
            //                     }
            //                 ]
            //             },
            //             {
            //                 xtype: 'panel',
            //                 flex: 2,
            //                 padding: 5,
            //                 style: 'color:#32AFE7;font-size:14px;',
            //                 layout: 'vbox',
            //                 items: [
            //                     {
            //                         xtype: 'label',
            //                         html: 'DEv Smith',
            //                         id: 'UserNameMyZone',
            //                         width: '100%'
            //                     },
            //                     {
            //                         xtype: 'label',
            //                         html: 'This is my friend and for you r testing only',
            //                         id: 'UserMessageMyZone',
            //                         width: 150
            //                     }
            //                 ]
            //             },
            //             {
            //                 xtype: 'spacer',
            //                 flex: 1
            //             }
            //         ]
            //     }
            // ]
            // ========================================
    },
     onCloseTap: function(button, e, eOpts) {
        Ext.getCmp('UserProfile').hide();
    }
});