/*
 * File: app/view/UserEmail.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DNB.view.UserEmail', {
    extend: 'Ext.Container',
    alias: 'widget.useremail',

    requires: [
        'Ext.Toolbar',
        'Ext.Spacer',
        'Ext.Button',
        'Ext.Panel',
        'Ext.field.Email'
    ],

    config: {
        centered: true,
        height: 200,
        id: 'UserEmail',
        style: 'background-color:white;',
        width: 300,
        modal: true,
        items: [
            {
                xtype: 'toolbar',
                cls: 'popheader',
                docked: 'top',
                items: [
                    {
                        xtype: 'spacer',
                        flex: 1
                    },
                    {
                        xtype: 'button',
                        html: '<div><img  width="16" src="resources/images/CloseBlueIcon.JPG"></div>',
                        itemId: 'Close',
                        margin: '0 -5 0 0',
                        ui: 'plain'
                    }
                ]
            },
            {
                xtype: 'panel',
                html: 'Twitter Signup Email',
                margin: 0,
                style: 'color:rgb(220, 178, 9);text-align:center;font-weight:bold;'
            },
            {
                xtype: 'emailfield',
                hidden: true,
                id: 'UserEmailAddress123',
                style: 'border-bottom:1px solid gray;',
                clearIcon: false,
                label: 'Email',
                placeHolder: 'email@example.com'
            },
            {
                xtype: 'emailfield',
                id: 'UserEmailAddress',
                margin: '20 0 0 10% 0',
                padding: 5,
                style: 'border:1px solid rgb(220, 178, 9);border-radius:3px;color:rgb(220, 178, 9);',
                width: '80%',
                clearIcon: false,
                placeHolder: 'johndoe@gmail.com'
            },
            {
                xtype: 'button',
                centered: false,
                cls: 'popbtn',
                docked: 'bottom',
                height: 50,
                itemId: 'SaveEmailAddress',
                style: 'color:white;background-color: rgb(220, 178, 9);',
                ui: 'plain',
                width: '100%',
                text: 'Submit'
            }
        ]
    }

});