/*
 * File: app/model/Notices.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */
Ext.define('DNB.model.Notices', {
    extend: 'Ext.data.Model',
    requires: ['Ext.data.Field'],
    config: {
        fields: [{
            name: 'id'
        }, {
            name: 'flyer'
        }, {
            name: 'title'
        }, {
            name: 'description'
        }, {
            name: 'notice_type'
        }, {
            name: 'venu_detail'
        }, {
            name: 'time_from'
        }, {
            name: 'time_to'
        }, {
            name: 'hot_five'
        }, {
            name: 'duration'
        }, {
            name: 'start_date'
        }, {
            name: 'end_date'
        }, {
            name: 'extra'
        }, {
            name: 'price'
        }, {
            name: 'total_likes'
        }, {
            name: 'total_comments'
        }, {
            name: 'total_favorites'
        }, {
            name: 'isLike'
        }, {
            name: 'total_views'
        }, {
            name: 'categoryIds'
        }, {
            name: 'phone_number'
        }, {
            name: 'email'
        }, {
            name: 'city'
        }, {
            name: 'state'
        }, {
            name: 'zip'
        }, {
            name: 'slot_no'
        }, {
            name: 'latitude'
        }, {
            name: 'longitude'
        }, {
            name: 'comment'
        }]
    }
});