/*
 * File: app/controller/Account.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DNB.controller.Account', {
    extend: 'Ext.app.Controller',
    alias: 'controller.account',

    config: {
        views: [
            'Account'
        ],

        control: {
            "button[itemId=ChangeEmailAddress]": {
                tap: 'onChangeEmailAddressButtonTap'
            },
            "button[itemId=ChangePassword]": {
                tap: 'onChangePasswordButtonTap'
            }
        }
    },

    onChangeEmailAddressButtonTap: function(button, e, eOpts) {
        if(Ext.getCmp('ChangEmail'))
            Ext.getCmp('ChangEmail').show();
        else
            Ext.Viewport.add({xtype:'changeemail'}).show();
        Ext.getCmp('UserNewEmailAddress').setValue(localStorage.getItem('email'));
    },

    onChangePasswordButtonTap: function(button, e, eOpts) {
        if(Ext.getCmp('ChangePassword'))
            Ext.getCmp('ChangePassword').show();
        else
            Ext.Viewport.add({xtype:'changepassword'}).show();
        var ChangePassword=Ext.getCmp('ChangePassword');
        ChangePassword.query('[itemId=oldpassword]')[0].setValue('');
        ChangePassword.query('[itemId=newpassword]')[0].setValue('');
        ChangePassword.query('[itemId=newconfirmpassword]')[0].setValue('');
    }

});