/*
 * File: app/controller/EventDetail.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DNB.controller.EventDetail', {
    extend: 'Ext.app.Controller',

    config: {
        views: [
            'EventDetail'
        ],
        refs: {
            
            back           : 'button[name=eventDetailBackButton]',
            calenderIcon   : 'button[name=eventDateButton]',
            mapIcon        : 'button[name=eventMapButton]'
            

        },

        control: {

            back : {
                tap : 'onBackTap'
            },
            calenderIcon : {
                tap : 'onEventDateTap'
            },
            
            mapIcon : {
                tap : 'onEventLocationButttonTap'
            },
            
            "image[itemId=viewInfoImage]": {
                tap: 'onViewInfoButtonTap'
            },
            "image[itemId=galleryImage]": {
                tap: 'onGalleryButtonTap'
            },
            "image[itemId=eventAttendingImage]": {
                tap: 'onEventAttendingButtonTap'
            },
            "image[itemId=shareImage]": {
                tap: 'onShareButtonTap'
            },
            "image[itemId=contactInfoImage]": {
                tap: 'onContactInfoButtonTap'
            },
            "image[itemId=listenAudiImage]": {
                tap: 'onAudioButtonTap'
            },
            "image[itemId=viewVideoImage]": {
                tap: 'onVideoButtonTap'
            },
            "image[itemId=flagNoticeImage]": {
                tap: 'onFlagNoticeButtonTap'
            },




            "button[itemId=viewInfoBtn]": {
                tap: 'onViewInfoButtonTap'
            },
            "button[itemId=galleryBtn]": {
                tap: 'onGalleryButtonTap'
            },
            "button[itemId=eventAttendingBtn]": {
                tap: 'onEventAttendingButtonTap'
            },
            "button[itemId=shareBtn]": {
                tap: 'onShareButtonTap'
            },
            "button[itemId=contactInfoBtn]": {
                tap: 'onContactInfoButtonTap'
            },
            "button[itemId=listenAudiBtn]": {
                tap: 'onAudioButtonTap'
            },
            "button[itemId=viewVideoBtn]": {
                tap: 'onVideoButtonTap'
            },
            "button[itemId=flagNoticeBtn]": {
                tap: 'onFlagNoticeButtonTap'
            },



            "button[itemId=search]": {
                tap: 'onSearchButtonTap'
            },
           
            "button[itemId=LikeButton]": {
                tap: 'onLikeButtonTap'
            },
            "button[itemId=EventCommentButton]": {
                tap: 'onEventCommentButtonTap'
            },
            "button[itemId=favoriteButton]": {
                tap: 'onFavoriteButtonTap'
            }
        }
    },
     init: function(application) {
        application.on([{
            event: 'showEventDetails',
            fn: this.onShowEventDetails,
            scope: this
        }
        ]);
    },

    onBackTap: function(button, e, eOpts) {
        if(eventDetailPageOpenFrom == 'MyZone'){
            ShowHideHomePages('HomeContainer' , 'MyZone');
        }else if(eventDetailPageOpenFrom == 'Home'){
             ShowHideHomePages('HomeContainer','Home');
        }else if(eventDetailPageOpenFrom == 'GoLive'){
             ShowHideHomePages('HomeContainer' , 'GoLive');
        }else{
            ShowHideHomePages('HomeContainer','Home');
        }
       
        
    },
   onEventDateTap: function(button, e, eOpts) {
                DNB.app.getController('Events').AddToCalendar();

    },

    onEventLocationButttonTap: function(button, e, eOpts) {
        var address=button.getText();
        console.log(address);
        mapPageOpenFrom='EventDetail';
        DNB.app.getController('Events').ShowMap(address);
    },

    onSearchButtonTap: function(button, e, eOpts) {
        Ext.getCmp('DNBView').hide();
        if(Ext.getCmp('EventSearch'))
            Ext.getCmp('EventSearch').show();
        else
            Ext.Viewport.add({xtype:'eventsearch'}).show();
        Ext.getStore('NoticesSearchStore').setData(NoticesSearchStoreData);
        Ext.getStore('NoticesSearchStore').clearFilter();
        if(categorySearchListData.length>0){
            for(var i=0;i<categorySearchListData.length;i++){
                categorySearchListData[i].isSelected='no';
            }
            Ext.getStore('EventCategorySearchStore').setData(categorySearchListData);
        }
    },

    onAudioButtonTap: function(button, e, eOpts) {
            var audioList=[];
            if(selectedEventDetail.Media.length>0){
                var iCount=1;
                for(j=0;j<selectedEventDetail.Media.length;j++){
                    if(selectedEventDetail.Media[j].type=='A' && selectedEventDetail.Media[j].url!=''){
                        selectedEventDetail.Media[j].title='Audio-'+iCount;
                        iCount++;
                        audioList.push(selectedEventDetail.Media[j]);
                    }
                }//media for
                if(audioList.length>0){
                    Ext.getStore('EventAudiosStore').setData(audioList);
                    ShowHideHomePages('EventAudiosContainer');
                }
                else
                    Ext.Msg.alert('','No audio found.');
            }//eo if
            else{
                Ext.Msg.alert('','Audio is not available to play!');
            }

    },

    onVideoButtonTap: function(button, e, eOpts) {
        //console.log(selectedEventDetail.Media);
        // m = selectedEventDetail.Media
        var vedioList=[];
        if(selectedEventDetail.Media.length>0){
            var iCount=1;
            for(j=0;j<selectedEventDetail.Media.length;j++){
                if(selectedEventDetail.Media[j].type=='V' && selectedEventDetail.Media[j].url!=''){
                    selectedEventDetail.Media[j].title='Video-'+(iCount);
                    iCount++;
                    vedioList.push(selectedEventDetail.Media[j]);
                }
            }//media for
            if(vedioList.length>0){
                Ext.getStore('EventVideosStore').setData(vedioList);
                Ext.Viewport.query('eventvideoplayer')[0].setVideoUrl(selectedEventDetail.Media[0].url);
                // Ext.Viewport.query('eventvideoplayer')[0].setVideoUrl('https://www.youtube.com/watch?v=HQFvjYHsZ_w');
                // ShowHideHomePages('EventVideosContainer');
                ShowHideHomePages('EventVideoPlayerContainer');
            }
            else
                Ext.Msg.alert('','No video found.');
        }//eo if
        else{
            Ext.Msg.alert('','Video is not available to play!');
        }

    },

    onFlagNoticeButtonTap: function(button, e, eOpts) {
        if(isLogin==false){
            loginPageOpenFrom='EventDetail';
            Ext.getCmp('Login').show();
            Ext.getCmp('DNBView').hide();
            return;
        }
        else{
                Ext.Ajax.request({
                    url:DNB.util.Common.api.addFlag,
                    method:'POST',
                    params:{
                        notice_id:selectedEventDetail.Notice.id,
                        user_id:localStorage.getItem('userid')
                    },
                    success: function(res){
                        var res=Ext.decode(res.responseText).NoticeFlag;
                        Ext.Msg.alert('','Notice has been flagged !');
                        // Ext.Msg.alert('',res.mgs);

                    },failure:function(res){
                        Ext.Msg.alert('','Internet is not available.');
                    }
                });
        }
    },

    onContactInfoButtonTap: function(button, e, eOpts) {
        if(Ext.getCmp('ContactInfo'))
            Ext.getCmp('ContactInfo').show();
        else
            Ext.Viewport.add({xtype:'contactinfo'}).show();
    },

    onShareButtonTap: function(button, e, eOpts) {

        if(isLogin==false){
            loginPageOpenFrom='EventDetail';
            Ext.getCmp('Login').show();
            Ext.getCmp('DNBView').hide();
            return;
        }
        else{
            Ext.Viewport.setMasked({xtype:'loadmask',message:'Loading sharing information'});
            var imageurl=selectedEventDetail.Notice.flyer;

            var audioList=[];


            var vedioList=[];
            if(selectedEventDetail.Media.length>0){
                for(j=0;j<selectedEventDetail.Media.length;j++){
                    if(selectedEventDetail.Media[j].type=='V'){
                        vedioList.push(selectedEventDetail.Media[j].url);
                    }
                    else if(selectedEventDetail.Media[j].type=='A'){
                        audioList.push(audioBaseUrl+selectedEventDetail.Media[j].url);
                    }
                }//media for
            }//eo if

            var noticeLocation=selectedEventDetail.Notice.venu_detail+', '+selectedEventDetail.Notice.city+', '+
                selectedEventDetail.Notice.state+', '+selectedEventDetail.Notice.zip;
            var videoUrls=   vedioList.join(',');
            var audioUrls=   audioList.join(',');
            console.log(videoUrls);
            window.plugins.socialsharing.available(function(isAvailable) {
                Ext.Viewport.setMasked(false);
                if (isAvailable) {
                    window.plugins.socialsharing.share(selectedEventDetail.Notice.title, 'My subject', imageBaseUrl + imageurl, null, function () { }, function (e) {alert("error: " + e);});

                    //window.plugins.socialsharing.share(selectedEventDetail.Notice.title, 'My subject', imageBaseUrl+imageurl, null,videoUrls,audioUrls,noticeLocation, function(){}, function(e){alert("error: " + e);});

                }
            });
        }
    },

    onEventAttendingButtonTap: function(button, e, eOpts) {

        if(isAlreadyAttendNotice){
            Ext.Msg.alert('','You have already added this notice.');
            return;
        }
        else if(isLogin==false){
            loginPageOpenFrom='EventDetail';
            Ext.getCmp('Login').show();
            Ext.getCmp('DNBView').hide();
            return;
        }
        else{
            Ext.Msg.confirm('Adding to RSVP.','Are you sure?',function(btn){
                if(btn=='yes'){
                    Ext.Ajax.request({
                        url:DNB.util.Common.api.attendNotice,
                        method:'POST',
                        params:{
                            notice_id:selectedEventDetail.Notice.id,
                            user_id:localStorage.getItem('userid')
                        },
                        success: function(res){
                            isAlreadyAttendNotice=true;
                            Ext.Ajax.request({
                                url:DNB.util.Common.api.getNoticeById(selectedEventDetail.Notice.id),
                                success: function(res){
                                    var res=Ext.decode(res.responseText);
                                    selectedEventDetail=res.response_data;
                                    Ext.getCmp('eventAttendingImage').setHtml(selectedEventDetail.NoticeAttend.length);
                                    
                                },failure:function(res){
                                    Ext.Msg.alert('','Internet is not available.');
                                }
                            });
                        },failure:function(res){
                            Ext.Msg.alert('','Internet is not available.');
                        }
                    });
                }
            });
        }
    },

    onViewInfoButtonTap: function(button, e, eOpts) {
        if(Ext.getCmp('EventDescriptionView'))
            Ext.getCmp('EventDescriptionView').show();
        else
            Ext.Viewport.add({xtype:'eventdescriptionview'}).show();
        Ext.getCmp('EventDescriptionInfo').setHtml(selectedEventDetail.Notice.description==null?'No information available to view.':selectedEventDetail.Notice.description);
    },

    onGalleryButtonTap: function(button, e, eOpts) {

        if(selectedEventDetail.Media.length>0){
            var GalleryList=[];
            for(j=0;j<selectedEventDetail.Media.length;j++){
                if(selectedEventDetail.Media[j].type=='I'){
                    GalleryList.push(selectedEventDetail.Media[j]);
                }
            }//media for
            //console.log(GalleryList.length);
            if(GalleryList.length>0){
                Ext.getCmp('MainTabView').setActiveItem(2);
                Ext.getCmp('AlbumContainer').hide();
                Ext.getCmp('GalleryImageContainer').hide();
                Ext.getCmp('GalleryContainer').show();
                Ext.getCmp('GalleryPanel').removeAll();
                galleryPageOpenFrom='EventDetail';
                DNB.app.getController('Events').fnShowGallery(selectedEventDetail.Notice.id,GalleryList);
            }
            else{
                Ext.Msg.alert('','No gallery found.');
            }
        }
        else{
            Ext.Msg.alert('','No gallery found.');
        }
    },

    onLikeButtonTap: function(button, e, eOpts) {
        if(isAlreadyLikedNotice){
            Ext.Msg.alert('','You have already liked this notice.');
            return;
        }
        else if(isLogin==false){
            loginPageOpenFrom='EventDetail';
            Ext.getCmp('Login').show();
            Ext.getCmp('DNBView').hide();
            return;
        }
        else{
            Ext.Viewport.setMasked({xtype:'loadmask',message:'Saving  Like...'});
            Ext.Ajax.request({
                url:DNB.util.Common.api.addLike,
                method:'POST',
                params:{
                    notice_id:selectedEventDetail.Notice.id,
                    user_id:localStorage.getItem('userid')
                },
                success: function(res){
                    isAlreadyLikedNotice=true;
                    var res=Ext.decode(res.responseText);
                     Ext.Msg.alert('','Notice liked successfully.');
                    Ext.Ajax.request({
                        url:DNB.util.Common.api.getNoticeById(selectedEventDetail.Notice.id),
                        success: function(res){
                            Ext.Viewport.setMasked(false);
                            var res=Ext.decode(res.responseText);
                            selectedEventDetail=res.response_data;
                            Ext.getCmp('LikeButtonOnEventDetail').setText('<div  class="social">'+res.response_data.Like.length+'</div><div style="padding-top: 5px;"><img width="30px" height="30px" src="resources/images/likes.png" /></div>');
                        },failure:function(res){
                            Ext.Viewport.setMasked(false);
                            Ext.Msg.alert('','Internet is not available.');
                        }
                    });
                },failure:function(res){
                    Ext.Viewport.setMasked(false);
                    Ext.Msg.alert('','Internet is not available.');
                }
            });
        }
    },

    onEventCommentButtonTap: function(button, e, eOpts) {
        if(isLogin==false){
            loginPageOpenFrom='EventDetail';
            Ext.getCmp('Login').show();
            Ext.getCmp('DNBView').hide();
            return;
        }
        else
        {
            Ext.getCmp('DNBView').hide();
            commentEventId=selectedEventDetail.Notice.id;
            if(Ext.getCmp('EventComment'))
                Ext.getCmp('EventComment').show();
            else
                Ext.Viewport.add({xtype:'eventcomment'}).show();
            commentPageOpenFrom='EventDetail';
            DNB.app.getController('Events').GetEventCommentList(commentEventId);
        }
    },

    onFavoriteButtonTap: function(button, e, eOpts) {
        if(isAlreadyFavoriteNotice){
            Ext.Msg.alert('','Notice already added to favourites.');
            return;
        }
        else if(isLogin==false){
            loginPageOpenFrom='EventDetail';
            Ext.getCmp('Login').show();
            Ext.getCmp('DNBView').hide();
            return;
        }else{
                Ext.Viewport.setMasked({xtype:'loadmask',message:'Adding to favourites...'});
                Ext.Ajax.request({
                    url:DNB.util.Common.api.addFavorite,
                    method:'POST',
                    params:{
                        notice_id:selectedEventDetail.Notice.id,
                        user_id:localStorage.getItem('userid')
                    },
                    success: function(res){
                        isAlreadyFavoriteNotice=true;
                        var res=Ext.decode(res.responseText);
                        Ext.Msg.alert('','Added to favourites.');
                        Ext.Ajax.request({
                            url:DNB.util.Common.api.getNoticeById(selectedEventDetail.Notice.id),
                            success: function(res){
                                Ext.Viewport.setMasked(false);
                                var res=Ext.decode(res.responseText);
                                selectedEventDetail=res.response_data;
                                Ext.getCmp('favoriteButton').setText('<div  class="social">'+res.response_data.Favorite.length+'</div><div style="border-right: 1px solid #fff;padding-top: 5px;"><img width="30px" height="30px" src="resources/images/favs.png" /></div>');

                            },failure:function(res){
                                Ext.Viewport.setMasked(false);
                                Ext.Msg.alert('','Internet is not available.');
                            }
                        });

                    },failure:function(res){
                        Ext.Viewport.setMasked(false);
                        Ext.Msg.alert('','Internet is not available.');
                    }
                });
        }
    },
    onShowEventDetails : function(response){
        if(window.innerHeight==1024){
            Ext.getCmp('ViewGalleryAttendingPanel').setHeight(200);
            Ext.getCmp('ShareTotalViewContactInfoPanel').setHeight(200);
            Ext.getCmp('AudioVideoFlagPanel').setHeight(200);
        }
        selectedEventDetail=response;
                console.log(selectedEventDetail);
                if(selectedEventDetail.status!=null && selectedEventDetail.status!=undefined){
                     Ext.Viewport.setMasked(false);
                    Ext.Msg.alert(selectedEventDetail.messge);
                    return;
                }
                if(selectedEventDetail.NoticeCategory && selectedEventDetail.NoticeCategory.length>0){
                    var catId=selectedEventDetail.NoticeCategory[0].categorie_id;
                    if(noticesCategoryListData.length>0){
                        var catRec=Ext.getStore('EventCategoryStore').findRecord('id',catId);
                        if(catRec!=null && catRec!=undefined){
                            console.log(catRec);
                            console.log(catRec.get('title'));
                            Ext.getCmp('EventDetailToolbarTitle').setTitle(catRec.get('title'));
                        }
                    }
                }
                isAlreadyAttendNotice=false;
                Ext.getCmp('MainTabView').setActiveItem(0);

                
                ShowHideHomePages('EventDetailContainer');
                var EventLocation=selectedEventDetail.Notice.city;
                
                EventLocation=EventLocation.substr(0,10);
                Ext.getCmp('EventLocationButtton').setText(EventLocation);

                Ext.getCmp('EventImage').setSrc((selectedEventDetail.Notice.flyer==null || selectedEventDetail.Notice.flyer.length==0) ? 'resources/images/noImage.jpg':(imageBaseUrl +selectedEventDetail.Notice.flyer));
                Ext.get('search-bg').setStyle({
                    backgroundImage: 'url(' + imageBaseUrl + selectedEventDetail.Notice.flyer + ')'
                })
                Ext.getCmp('EventTitle').setText(selectedEventDetail.Notice.title);
                Ext.getCmp('EventDate').setHtml(selectedEventDetail.Notice.end_date);
                var startTime=selectedEventDetail.Notice.time_from;
                var sh='',sm='';
                
                if(startTime!=null){
                    startTime=startTime.split(':');
                    if(startTime[0].length==1)
                        startTime[0]='0'+startTime[0];
                    if(startTime[1].length==1)
                        startTime[1]='0'+startTime[1];
                    if(startTime[1].indexOf(' ')>=0)
                        startTime[1]=startTime[1].split(' ')[0];
                    if(startTime[1].indexOf('AM')>=0)
                        startTime[1]=startTime[1].replace('AM','');
                    if(startTime[1].indexOf('PM')>=0)
                        startTime[1]=startTime[1].replace('PM','');
                }
                var endTime=selectedEventDetail.Notice.time_to;
                var eh='',em='';
                
                if(endTime!=null){
                    endTime=endTime.split(':');
                    if(endTime[0].length==1)
                        endTime[0]='0'+endTime[0];
                    if(endTime[1].length==1)
                        endTime[1]='0'+endTime[1];
                    if(endTime[1].indexOf(' ')>=0)
                        endTime[1]=endTime[1].split(' ')[0];
                    if(endTime[1].indexOf('AM')>=0)
                        endTime[1]=endTime[1].replace('AM','');
                    if(endTime[1].indexOf('PM')>=0)
                        endTime[1]=endTime[1].replace('PM','');
                }
                
                Ext.getCmp('EventTime').setText(startTime[0]+':'+startTime[1]+'&nbsp;-&nbsp;'+endTime[0]+':'+endTime[1]);
                Ext.getCmp('favoriteButton').setText('<div  class="social">'+selectedEventDetail.Favorite.length+'</div><div style="border-right: 1px solid #fff;padding-top: 5px;"><img width="30px" height="30px" src="resources/images/favs.png" /></div>');
                Ext.getCmp('EventCommentButton').setText('<div  class="social">'+selectedEventDetail.Comment.length+'</div><div style="border-right: 1px solid #fff;padding-top: 5px;"><img width="30px" height="30px" src="resources/images/comments.png" /></div>');
                Ext.getCmp('LikeButtonOnEventDetail').setText('<div  class="social">'+selectedEventDetail.Like.length+'</div><div style="padding-top: 5px;"><img width="30px" height="30px" src="resources/images/likes.png" /></div>');
                Ext.getCmp('eventAttendingImage').setHtml(selectedEventDetail.NoticeAttend.length);
                Ext.getCmp('eventTotalViewImage').setHtml(selectedEventDetail.NoticeView.length);
                isAlreadyLikedNotice=false;
                
                if(isLogin && selectedEventDetail.Like.length>0){
                    for(var j=0;j<selectedEventDetail.Like.length;j++){
                        if(selectedEventDetail.Like[j].user_id==localStorage.getItem('userid')){
                            isAlreadyLikedNotice=true;
                            Ext.getCmp('LikeButtonOnEventDetail').setText('<div class="social">'+selectedEventDetail.Like.length+
                                                                          '</div><div style="padding-top: 5px;"><img width="32px" height="32px" src="resources/images/likes.png" /></div>');
                            break;
                        }
                    }
                }
                isAlreadyAttendNotice=false;
                if(isLogin && selectedEventDetail.NoticeAttend.length>0){
                    for(var j=0;j<selectedEventDetail.NoticeAttend.length;j++){
                        if(selectedEventDetail.NoticeAttend[j].user_id==localStorage.getItem('userid')){
                            isAlreadyAttendNotice=true;
                            break;
                        }
                    }
                }
                isAlreadyFavoriteNotice=false;
                if(isLogin && selectedEventDetail.Favorite.length>0){
                    for(var j=0;j<selectedEventDetail.Favorite.length;j++){
                        if(selectedEventDetail.Favorite[j].user_id==localStorage.getItem('userid')){
                            isAlreadyFavoriteNotice=true;
                            break;
                        }
                    }
                }

                if(selectedEventDetail.User){
                    if(!Ext.getCmp('ContactInfo')){
                        Ext.Viewport.add({xtype:'contactinfo'});
                        Ext.getCmp('ContactInfo').hide();
                    }
                    Ext.getCmp('EventManagerContactNo').setHtml('<img width="32px" src="resources/images/phone.png"/>'+
                                                                '<a href="tel:'+selectedEventDetail.Notice.phone_number+'">'+
                                                                selectedEventDetail.Notice.phone_number+'</a>');
                    var imgphone_number='<div style="width: 14px;float: left;">'+
                        '<img width="32px" src="resources/images/phone.png"/></div>';
                    var padding=(deviceName=='tablet'?'40%':'5%');
                    var dateText='<div style="margin-left:20px;margin-top: 3px;float: left;"><a href="tel:'+
                        selectedEventDetail.Notice.phone_number+'">'+
                        selectedEventDetail.Notice.phone_number+'</a></div>';


                    //EventManagerWebsite
                    var website;
                           website=((selectedEventDetail.Notice.website=="null"
                                            || selectedEventDetail.Notice.website==null)?"":selectedEventDetail.Notice.website);

                    Ext.getCmp('EventManagerWebsite').setHtml('<img width="32px" src="resources/images/website.png"/>'+
                                                              '<a href="#" onclick="fnShowNoticeWebsite();">'+
                                                              ((selectedEventDetail.Notice.website=="null"
                                                                || selectedEventDetail.Notice.website==null)?"":selectedEventDetail.Notice.website)+'</a>');
                    var imgwebsite='<div style="width: 14px;float: left;">'+
                        '<img width="32px" src="resources/images/website.png"/></div>';

                    dateText='<div style="margin-left:20px;margin-top: 3px;float: left;">'+
                        '<a href="#" onclick="fnShowNoticeWebsite();">'+
                        ((selectedEventDetail.Notice.website=="null"
                          || selectedEventDetail.Notice.website==null)?"":selectedEventDetail.Notice.website)+'</a></div>';

                    //EventManagerEmail
                    var imgEmail='<div style="width: 14px;float: left;">'+
                        '<img width="32px" src="resources/images/email.png"/></div>';

                    dateText='<div style="margin-left:20px;margin-top: 3px;float: left;"><a href="mailto:'+
                        selectedEventDetail.Notice.email+'">'+
                        selectedEventDetail.Notice.email+'</a></div>';
                    Ext.getCmp('EventManagerEmail').setHtml('<img width="32px" src="resources/images/email.png"/>'+
                                                            '<div><a href="mailto:'+selectedEventDetail.Notice.email+'">'+
                                                            selectedEventDetail.Notice.email+'</a></div>');

                    Ext.getCmp('contactinfoparel').setData({phone:selectedEventDetail.Notice.phone_number,
                                                                    website:website,
                                                                    email:selectedEventDetail.Notice.email});
                }//eo if
                //console.log(selectedEventDetail.Notice.hot_five);
                console.log(promotionsHotFiveData);
                if(selectedEventDetail.Notice.hot_five=='Yes'){
                    promotionsData=promotionsHotFiveData;
                    var promotionTempData=[];
                    if(promotionCategorySelectedList.length>0){
                        for(var k=0;k<promotionsHotFiveData.length;k++){
                            for(var j=0;j<promotionCategorySelectedList.length;j++){
                                console.log(promotionsHotFiveData[k].promotionCategory);
                                if(promotionsHotFiveData[k].promotionCategory.indexOf(':'+promotionCategorySelectedList[j]+':')>=0){
                                    promotionTempData.push(promotionsHotFiveData[k]);
                                    break;
                                }
                            }
                        }
                        promotionsData=[];
                        promotionsData=promotionTempData;
                    }else{
                        promotionsData=promotionsHotFiveData;
                    }
                    console.log(promotionsData);
                }else{
                    DNB.app.getController('Events').FilterPromotions();
                }
                
                currentBannerPageName='promotionImageOnDetail';
                currentPromotionIndex = 0;
                promotionStartFlag = true;
                if(!promotionFlag){
                    DNB.app.getController('Events').ShowPromotions(currentPromotionIndex, currentBannerPageName);
                }
                Ext.Viewport.setMasked(false);

    },

    FillEventDetail: function(eventInfo) {

        console.log('fnShowEventDetailPageFromHome:'+eventInfo);
        Ext.Viewport.setMasked({xtype:'loadmask',message:'Loading'});
        var servicesController = DNB.app.getController('ServicesController'); 
        var params = {notice_id:eventInfo.id,
                user_id:localStorage.getItem('userid')};
        servicesController.fillEventDetails(params);
       
    }

});