/*
 * File: app/controller/Home.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DNB.controller.Home', {
    extend: 'Ext.app.Controller',

    config: {
        views: [
            'Home'
        ],
        refs: {
            
            hotFiveListDataView           : 'dataview[name=hotFiveListDataView]',
            otherEventSearchByDateButton  : 'button[name=otherEventSearchByDateButton]',
            categorylistmenuButton        : 'button[name=categorylistmenuButton]',
            OtherNoticeListOnHomePage     : 'dataview[name=OtherNoticeListOnHomePage]',
            searchButton                  : 'button[name=searchButton]'
           

        },

        control: {
            hotFiveListDataView : {
                itemtap : 'onHotFiveListItemTap'
            },
            otherEventSearchByDateButton: {
                tap: 'onOtherEventSearchByDateButtonTap'
            },
            categorylistmenuButton : {
                tap: 'onCategorylistmenuTap'
            },
            OtherNoticeListOnHomePage : {
                itemtap : 'onOtherNoticeListOnHomePageItemTap'
            },
            searchButton : {
                tap : 'onSearchTap'
            },


            "image[itemId=AddEvent]": {
                tap: 'onAddEventImageTap'
            },
            "image[itemId=addpromo]": {
                tap: 'onAddPromoImageTap'
            }
        }
    },

    onHotFiveListItemTap: function(dataview, index, target, record, e, eOpts) {
        if(e.target.className=='venudetail'){
            mapPageOpenFrom='Home';
            selectedEventDetail.Notice=record.data;
            DNB.app.getController('Events').ShowMap(record.data.venu_detail);
        }
        else if(e.target.className=='eventdate'){
            selectedEventDetail.Notice=record.data;
            DNB.app.getController('Events').AddToCalendar();
        }
        else{
            DNB.app.getController('EventDetail').FillEventDetail({id:record.data.id});
        }
    },

    onCategorylistmenuTap: function(button, e, eOpts) {
        if(Ext.getCmp('Category'))
            Ext.getCmp('Category').show();
        else
        Ext.Viewport.add({xtype:'category'}).show();
        Ext.getStore('EventCategoryStore').setData(categoryListData);
        Ext.getStore('PromotionsCategoryStore').setData(promotionsCategoryListData);
        Ext.getCmp('CategoryUserProfilePanel').show();
        var userImage = localStorage.getItem('image');
        if(userImage=='' || userImage == null ){
            Ext.getCmp('UserProfileImageOnCategory').setSrc('resources/images/default-user.png');
        }else{
            Ext.getCmp('UserProfileImageOnCategory').setSrc(imageBaseUrl+localStorage.getItem('image'));
        }
            

        Ext.getCmp('UserNameOnCategory').setHtml(localStorage.getItem('username'));//+' '+localStorage.getItem('Last_name'));
        Ext.getCmp('UserMessageOnCategory').setHtml('<b>'+localStorage.getItem('usermessage')+'</b>');
    },
    onOtherNoticeListOnHomePageItemTap: function(dataview, index, target, record, e, eOpts) {
        // console.log(e);return;
        // debugger
        console.log(record);
        // console.log(e);
        if(e.target.id =='notice_calendericon'){
            console.log('calendar clicked')
            selectedEventDetail.Notice=record.data;
            DNB.app.getController('Events').AddToCalendar();

        }else if (e.target.id =='notice_mapicon'){
            console.log('map clicked')
            mapPageOpenFrom='Home';
            selectedEventDetail.Notice=record.data;
            DNB.app.getController('Events').ShowMap(record.data.venu_detail);
        }else{
            console.log('Image clicked')
            DNB.app.getController('EventDetail').FillEventDetail({id:record.data.id});
        
        }
    },

    onSearchTap: function(button, e, eOpts) {
        Ext.getCmp('DNBView').hide();
        if(Ext.getCmp('EventSearch'))
            Ext.getCmp('EventSearch').show();
        else
            Ext.Viewport.add({xtype:'eventsearch'}).show();
        //Ext.getStore('EventCategorySearchStore').setData(categorySearchListData);
        //Ext.getStore('NoticesSearchStore').clearFilter();
        //Ext.getCmp('eventsearchfield').setValue('a');
        if(categorySearchListData.length>0){
            for(var i=0;i<categorySearchListData.length;i++){
                categorySearchListData[i].isSelected='no';
            }
            Ext.getStore('EventCategorySearchStore').setData(categorySearchListData);
        }
        Ext.getStore('NoticesSearchStore').setData(NoticesSearchStoreData);

    },
    onOtherEventSearchByDateButtonTap: function(button, e, eOpts) {
        isCalendaralreadyOpen=false;
        isDateSelectedFromCalendar=false;
        calendarOpenFromPage='Home';
        setTimeout(function(){
             if(Ext.getCmp('Calendar'))
                 Ext.getCmp('Calendar').show();
             else
                 Ext.Viewport.add({xtype:'calendar'}).show();
             Ext.getCmp('Calendar').setDateValue(currentSearchDate);
             Ext.getCmp('Calendar').setSelectedDate(currentSearchDate);
         },400);

    },


    onAddEventImageTap: function(image, e, eOpts) {
        if(isLogin==false){
            loginPageOpenFrom='HomeContainer';
            if(Ext.getCmp('Login'))
                Ext.getCmp('Login').show();
            else
                Ext.Viewport.add({xtype:'login'}).show();
            Ext.getCmp('DNBView').hide();
            return;
        }else{
            categoryDataToAdd=[];
            categoryDataToAdd=noticesCategoryListData;


            isEditNotice=false;
            selectedCategoryIDsToAdd='';

            categoryMultiSelectOpenFromPage='AddEvent';
            Ext.getCmp('DNBView').hide();
            if(Ext.getCmp('AddEvent'))
                Ext.getCmp('AddEvent').show();
            else
                Ext.Viewport.add({xtype:'addevent'}).show();
            noticeImages=[];
            Ext.getCmp('EventImagesListPanel').hide();
            Ext.getCmp('NoticeImagPanel').setHeight(50);
            // Ext.getCmp('noticeImagPanelOnAddNoticePage').setHeight(50);
            

            DNB.app.getController('Events').ResetNoticeForm();
            Ext.getCmp('NoticeTitleToolbar').setTitle('Add Notice');
            Ext.getStore('FreeLocationsStore').setData(DNB.util.Common.freeLocations);
            if(deviceName=='phone'){//deviceOSName=='ios' &&
                if(deviceHeight>600){
                    Ext.getCmp('EventHotFive').setLabelWidth('73%');
                    Ext.getCmp('EventComments').setLabelWidth('73%');
                }
                else{
                    Ext.getCmp('EventHotFive').setLabelWidth('69%');
                    Ext.getCmp('EventComments').setLabelWidth('69%');
                }
            }
            var d=new Date();
            var m=d.getMonth()+1;
            var y=d.getFullYear();
            var day=d.getDate();
            // Ext.getCmp('EventStartDate').setValue({month:m,day:day,year:y});
            // Ext.getCmp('EventEndDate').setValue({month:m,day:day,year:y});
            Ext.getCmp('EventStartDate').setValue(new Date());
            Ext.getCmp('EventEndDate').setValue(new Date());

        }
    },

    onAddPromoImageTap: function(image, e, eOpts) {
        if(isLogin==false){
            loginPageOpenFrom='HomeContainer';
            Ext.getCmp('Login').show();
            Ext.getCmp('DNBView').hide();
            return;
        }else{
            selectedCategoryIDsToAdd='';
            categoryDataToAdd=[];
            categoryDataToAdd=promotionsCategoryListData;
            categoryMultiSelectOpenFromPage='AddPromotion';
            Ext.getCmp('DNBView').hide();
            if(Ext.getCmp('AddPromotion'))
                Ext.getCmp('AddPromotion').show();
            else
                Ext.Viewport.add({xtype:'addpromotion'}).show();
            DNB.app.getController('Events').ResetPromotionForm();
            Ext.getCmp('PromotionTitleToolbar').setTitle('Add Promotion');
            if(deviceName=='phone'){//deviceOSName=='ios' &&
                if(deviceHeight>600){
                    Ext.getCmp('PromotionHotFive').setLabelWidth('73%');

                }
                else{
                    Ext.getCmp('PromotionHotFive').setLabelWidth('69%');

                }
            }
            var d=new Date();
            var m=d.getMonth()+1;
            var y=d.getFullYear();
            var day=d.getDate();
            // Ext.getCmp('PromotionFromDate').setValue({month:m,day:day,year:y});
            // Ext.getCmp('PromotionToDate').setValue({month:m,day:day,year:y});
            // Ext.getCmp('EventStartDate').setValue({month:m,day:day,year:y});
            // Ext.getCmp('EventEndDate').setValue({month:m,day:day,year:y});
            Ext.getCmp('PromotionFromDate').setValue(new Date());
            Ext.getCmp('PromotionToDate').setValue(new Date());
        }
    }

});